/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "380px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1920px",
      "4xl": "2560px",
    },
    extend: {
      containers: {
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "40rem",
        "2xl": "48rem",
      },
      colors: {
        "on-background": "#191c1e",
        "primary-container": "#3b3b3b",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#6a758a",
        "surface-dim": "#d8dadc",
        "on-primary-fixed": "#ffffff",
        "on-secondary-container": "#000000",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#000000",
        "on-secondary-fixed": "#000000",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#ffffff",
        "outline-variant": "#c6c6c6",
        "on-secondary": "#000000",
        "on-primary-fixed-variant": "#ffffff",
        "primary": "#000000",
        "secondary": "#ffffff",
        "secondary-fixed-dim": "#ffffff",
        "secondary-fixed": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#3c475a",
        "on-tertiary-fixed-variant": "#d8e3fb",
        "outline": "#777777",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-tint": "#5e5e5e",
        "on-primary-container": "#ffffff",
        "tertiary": "#313c4f",
        "on-error-container": "#410002",
        "background": "#f7f9fb",
        "on-error": "#ffffff",
        "secondary-container": "#f2f2f2",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#5e5e5e",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "primary-fixed-dim": "#474747",
        "tertiary-fixed": "#545f73",
        "on-surface-variant": "#474747",
        /* shadcn semantic aliases. Keep these mapped to the storefront token
           system so generated primitives remain brand-consistent. */
        foreground: "#191c1e",
        muted: "#f2f4f6",
        "muted-foreground": "#474747",
        card: "#ffffff",
        "card-foreground": "#191c1e",
        border: "#c6c6c6",
        input: "#c6c6c6",
        ring: "#5e5e5e",
        "primary-foreground": "#ffffff",
        "secondary-foreground": "#000000",
        destructive: "#ba1a1a",
        "destructive-foreground": "#ffffff",
        popover: "#ffffff",
        "popover-foreground": "#191c1e",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontSize: {
        "fluid-xs": ["clamp(0.75rem, 0.7rem + 0.25vw, 0.875rem)", { lineHeight: "1.35" }],
        "fluid-sm": ["clamp(0.875rem, 0.8rem + 0.35vw, 1rem)", { lineHeight: "1.45" }],
        "fluid-base": ["clamp(1rem, 0.9rem + 0.5vw, 1.125rem)", { lineHeight: "1.5" }],
        "fluid-lg": ["clamp(1.125rem, 1rem + 0.6vw, 1.25rem)", { lineHeight: "1.4" }],
        "fluid-2xl": ["clamp(1.5rem, 1.2rem + 1.5vw, 2rem)", { lineHeight: "1.15" }],
        "fluid-4xl": ["clamp(2.25rem, 1.5rem + 3.75vw, 3.5rem)", { lineHeight: "1.05" }],
      },
    },
  },
  plugins: [],
};
