import { archiveWorkerCmsComponentForAdmin, fetchWorkerCmsComponentForAdmin, publishWorkerCmsComponentForAdmin, updateWorkerCmsComponentForAdmin } from "@/lib/worker-admin-bridge";
import { getCorrelationId } from "@/lib/request-correlation";
type Context = { params: Promise<{ id: string }> };
export const dynamic = "force-dynamic";
export async function GET(request: Request, ctx: Context) { const requestId = getCorrelationId(request); const { id } = await ctx.params; const response = await fetchWorkerCmsComponentForAdmin(id); return response ?? new Response(JSON.stringify({ error: "Worker backend is unavailable", requestId }), { status: 503 }); }
async function readBody(request: Request) { const requestId = getCorrelationId(request); const key = request.headers.get("Idempotency-Key")?.trim() ?? null; if (!key) return { requestId, key, value: null as Record<string, unknown> | null, error: new Response(JSON.stringify({ error: "Idempotency-Key is required", requestId }), { status: 400 }) }; try { const raw = await request.text(); if (raw.length > 512 * 1024) throw new Error("large"); const parsed = JSON.parse(raw) as unknown; if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("invalid"); return { requestId, key, value: parsed as Record<string, unknown>, error: null }; } catch { return { requestId, key, value: null as Record<string, unknown> | null, error: new Response(JSON.stringify({ error: "Invalid JSON body", requestId }), { status: 400 }) }; } }
export async function PATCH(request: Request, ctx: Context) { const [{ id }, parsed] = await Promise.all([ctx.params, readBody(request)]); if (parsed.error) return parsed.error; if (!parsed.value || !parsed.key) return new Response(JSON.stringify({ error: "Invalid request", requestId: parsed.requestId }), { status: 400 }); const response = await updateWorkerCmsComponentForAdmin(id, parsed.value, parsed.key); return response ?? new Response(JSON.stringify({ error: "Worker backend is unavailable", requestId: parsed.requestId }), { status: 503 }); }
export async function POST(request: Request, ctx: Context) { const [{ id }, parsed] = await Promise.all([ctx.params, readBody(request)]); if (parsed.error) return parsed.error; if (!parsed.value || !parsed.key) return new Response(JSON.stringify({ error: "Invalid request", requestId: parsed.requestId }), { status: 400 }); const response = await publishWorkerCmsComponentForAdmin(id, parsed.value, parsed.key); return response ?? new Response(JSON.stringify({ error: "Worker backend is unavailable", requestId: parsed.requestId }), { status: 503 }); }
export async function DELETE(request: Request, ctx: Context) { const requestId = getCorrelationId(request); const { id } = await ctx.params; const key = request.headers.get("Idempotency-Key")?.trim(); const version = Number(new URL(request.url).searchParams.get("version")); if (!key) return new Response(JSON.stringify({ error: "Idempotency-Key is required", requestId }), { status: 400 }); if (!Number.isSafeInteger(version) || version < 1) return new Response(JSON.stringify({ error: "version required", requestId }), { status: 400 }); const response = await archiveWorkerCmsComponentForAdmin(id, version, key); return response ?? new Response(JSON.stringify({ error: "Worker backend is unavailable", requestId }), { status: 503 }); }
