/** Stable codes returned by `/api/checkout/available-payment-methods` (client-safe). */

export const CHECKOUT_AVAILABILITY = {
  OK: "OK",
  MISSING_CHECKOUT_CONFIG: "MISSING_CHECKOUT_CONFIG",
  MISSING_REGION: "MISSING_REGION",
  MEDUSA_REGION_FETCH_FAILED: "MEDUSA_REGION_FETCH_FAILED",
  NO_PAYMENT_PROVIDERS: "NO_PAYMENT_PROVIDERS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PAYMENT_METHODS_LOAD_FAILED: "PAYMENT_METHODS_LOAD_FAILED",
} as const;

export type CheckoutAvailabilityCode =
  (typeof CHECKOUT_AVAILABILITY)[keyof typeof CHECKOUT_AVAILABILITY];

export const CHECKOUT_HARD_UNAVAILABLE_CODES: ReadonlySet<string> = new Set([
  CHECKOUT_AVAILABILITY.MISSING_CHECKOUT_CONFIG,
  CHECKOUT_AVAILABILITY.MISSING_REGION,
  CHECKOUT_AVAILABILITY.MEDUSA_REGION_FETCH_FAILED,
  CHECKOUT_AVAILABILITY.NO_PAYMENT_PROVIDERS,
  CHECKOUT_AVAILABILITY.INTERNAL_ERROR,
  CHECKOUT_AVAILABILITY.PAYMENT_METHODS_LOAD_FAILED,
]);

export function isCheckoutHardUnavailableCode(code: string | undefined): boolean {
  return Boolean(code && CHECKOUT_HARD_UNAVAILABLE_CODES.has(code));
}
