import { getCorrelationId } from "@/lib/request-correlation";
import { createWorkerAdminOperatorNoteForAdmin, fetchWorkerAdminOperatorNotesForAdmin } from "@/lib/worker-admin-bridge";

export const dynamic = "force-dynamic";

function response(body: unknown, status: number, requestId: string) { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "x-request-id": requestId } }); }
function query(request: Request) { const params = new URL(request.url).searchParams; return params.get("entity_type") && params.get("entity_id") ? params.toString() : null; }
export async function GET(request: Request) { const requestId = getCorrelationId(request); const params = query(request); if (!params) return response({ error: "entity_type and entity_id query params are required", requestId }, 400, requestId); const result = await fetchWorkerAdminOperatorNotesForAdmin(params); return result ?? response({ error: "Worker backend is unavailable", requestId }, 503, requestId); }
export async function POST(request: Request) { const requestId = getCorrelationId(request); const params = query(request); if (!params) return response({ error: "entity_type and entity_id query params are required", requestId }, 400, requestId); const key = request.headers.get("Idempotency-Key")?.trim(); if (!key) return response({ error: "Idempotency-Key is required", requestId }, 400, requestId); const length = Number(request.headers.get("content-length") ?? 0); if (length > 128 * 1024) return response({ error: "Payload too large", requestId }, 413, requestId); let body: Record<string, unknown>; try { const text = await request.text(); if (text.length > 128 * 1024) throw new Error("payload_too_large"); const parsed = JSON.parse(text) as unknown; if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("invalid_payload"); body = parsed as Record<string, unknown>; } catch (error) { const status = error instanceof Error && error.message === "payload_too_large" ? 413 : 400; return response({ error: status === 413 ? "Payload too large" : "Invalid JSON body", requestId }, status, requestId); } const result = await createWorkerAdminOperatorNoteForAdmin(params, body, key); return result ?? response({ error: "Worker backend is unavailable", requestId }, 503, requestId); }
