/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1e",
        "primary-container": "#3b3b3b",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#6a758a",
        "surface-dim": "#d8dadc",
        "on-primary-fixed": "#ffffff",
        "on-secondary-container": "#0d1c2f",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#2e3c50",
        "on-secondary-fixed": "#0d1c2f",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#ffffff",
        "outline-variant": "#c6c6c6",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#e2e2e2",
        "primary": "#000000",
        "secondary": "#515f74",
        "secondary-fixed-dim": "#9eacc4",
        "secondary-fixed": "#b9c7e0",
        "inverse-primary": "#c6c6c6",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#3c475a",
        "on-tertiary-fixed-variant": "#d8e3fb",
        "outline": "#777777",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#e2e2e2",
        "surface-tint": "#5e5e5e",
        "on-primary-container": "#ffffff",
        "tertiary": "#313c4f",
        "on-error-container": "#410002",
        "background": "#f7f9fb",
        "on-error": "#ffffff",
        "secondary-container": "#c7d5ee",
        "on-tertiary": "#d8e3fb",
        "primary-fixed": "#5e5e5e",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "primary-fixed-dim": "#474747",
        "tertiary-fixed": "#545f73",
        "on-surface-variant": "#474747",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
