/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--admin-background) / <alpha-value>)",
        foreground: "rgb(var(--admin-on-background) / <alpha-value>)",
        card: "rgb(var(--admin-surface-container-lowest) / <alpha-value>)",
        "card-foreground": "rgb(var(--admin-on-surface) / <alpha-value>)",
        popover: "rgb(var(--admin-surface-container-lowest) / <alpha-value>)",
        "popover-foreground": "rgb(var(--admin-on-surface) / <alpha-value>)",
        muted: "rgb(var(--admin-surface-container) / <alpha-value>)",
        "muted-foreground": "rgb(var(--admin-on-surface-variant) / <alpha-value>)",
        border: "rgb(var(--admin-outline-variant) / <alpha-value>)",
        input: "rgb(var(--admin-outline-variant) / <alpha-value>)",
        ring: "rgb(var(--admin-outline) / <alpha-value>)",
        destructive: "rgb(var(--admin-error) / <alpha-value>)",
        "on-background": "rgb(var(--admin-on-background) / <alpha-value>)",
        "primary-container": "rgb(var(--admin-primary-container) / <alpha-value>)",
        "on-surface": "rgb(var(--admin-on-surface) / <alpha-value>)",
        "surface-container-high": "rgb(var(--admin-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--admin-surface-container-highest) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--admin-on-tertiary-container) / <alpha-value>)",
        "tertiary-container": "rgb(var(--admin-tertiary-container) / <alpha-value>)",
        "surface-dim": "rgb(var(--admin-surface-dim) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--admin-on-primary-fixed) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--admin-on-secondary-container) / <alpha-value>)",
        "error-container": "rgb(var(--admin-error-container) / <alpha-value>)",
        "inverse-surface": "rgb(var(--admin-inverse-surface) / <alpha-value>)",
        "surface-bright": "rgb(var(--admin-surface-bright) / <alpha-value>)",
        "error": "rgb(var(--admin-error) / <alpha-value>)",
        "surface-container-low": "rgb(var(--admin-surface-container-low) / <alpha-value>)",
        "outline-variant": "rgb(var(--admin-outline-variant) / <alpha-value>)",
        "on-secondary": "rgb(var(--admin-on-secondary) / <alpha-value>)",
	        "primary": "rgb(var(--admin-primary) / <alpha-value>)",
	        "primary-foreground": "rgb(var(--admin-on-primary) / <alpha-value>)",
        "secondary": "rgb(var(--admin-secondary) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--admin-inverse-on-surface) / <alpha-value>)",
        "outline": "rgb(var(--admin-outline) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--admin-surface-container-lowest) / <alpha-value>)",
        "on-primary": "rgb(var(--admin-on-primary) / <alpha-value>)",
        "tertiary": "rgb(var(--admin-tertiary) / <alpha-value>)",
        "on-error-container": "rgb(var(--admin-on-error-container) / <alpha-value>)",
        "background": "rgb(var(--admin-background) / <alpha-value>)",
        "on-error": "rgb(var(--admin-on-error) / <alpha-value>)",
        "secondary-container": "rgb(var(--admin-secondary-container) / <alpha-value>)",
        "surface-container": "rgb(var(--admin-surface-container) / <alpha-value>)",
        "surface": "rgb(var(--admin-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--admin-on-surface-variant) / <alpha-value>)",
        "chart-1": "rgb(var(--admin-chart-1) / <alpha-value>)",
        "chart-2": "rgb(var(--admin-chart-2) / <alpha-value>)",
        "chart-3": "rgb(var(--admin-chart-3) / <alpha-value>)",
        "chart-4": "rgb(var(--admin-chart-4) / <alpha-value>)",
        "chart-5": "rgb(var(--admin-chart-5) / <alpha-value>)",
      },
      fontFamily: {
        heading: ["var(--admin-headline-font)", "Plus Jakarta Sans", "sans-serif"],
        headline: ["var(--admin-headline-font)", "Plus Jakarta Sans", "sans-serif"],
        body: ["var(--admin-body-font)", "Inter", "sans-serif"],
        label: ["var(--admin-body-font)", "Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "var(--admin-radius)",
        lg: "var(--admin-radius)",
        xl: "calc(var(--admin-radius) + 0.25rem)",
        full: "0.75rem",
        "4xl": "2rem",
      },
      spacing: {
        30: "7.5rem",
        34: "8.5rem",
        54: "13.5rem",
        68: "17rem",
        74: "18.5rem",
      },
      boxShadow: {
        xs: "0 1px 2px rgb(0 0 0 / 0.04)",
      },
    },
  },
  plugins: [],
};
