/** Exact palette images from the vendored Vvveb component registrations. */
export const UVS_SOURCE_IMAGES: Readonly<Record<string, string>> = {
  _base: "icons/icon.svg",
  "html/heading": "icons/heading.svg", "html/link": "icons/link.svg", "html/image": "icons/image.svg", "html/hr": "icons/hr.svg",
  "html/textinput": "icons/text_input.svg", "html/selectinput": "icons/select_input.svg", "html/textareainput": "icons/text_area.svg",
  "html/radiobutton": "icons/radio.svg", "html/checkbox": "icons/checkbox.svg", "html/fileinput": "icons/text_input.svg",
  "html/video": "icons/video.svg", "html/button": "icons/button.svg", "html/paragraph": "icons/paragraph.svg",
  "html/blockquote": "icons/blockquote.svg", "html/list-item": "icons/list.svg", "html/list": "icons/list.svg",
  "html/preformatted": "icons/paragraph.svg", "html/form": "icons/form.svg", "html/tablerow": "icons/table.svg",
  "html/tablecell": "icons/table.svg", "html/tableheadercell": "icons/table.svg", "html/tablebody": "icons/table.svg",
  "html/tablefooter": "icons/table.svg", "html/tablehead": "icons/table.svg", "html/table": "icons/table.svg",
  "html/audio": "icons/audio.svg", "html/pdf": "icons/pdf.svg", "html/embed": "icons/embed.svg",
  "html/html": "icons/posts.svg", "html/iframe": "icons/file.svg",
  "html/container": "icons/container.svg", "html/btn": "icons/button.svg", "html/buttongroup": "icons/button_group.svg",
  "html/buttontoolbar": "icons/button_toolbar.svg", "html/alert": "icons/alert.svg", "html/badge": "icons/badge.svg",
  "html/card": "icons/panel.svg", "html/listgroup": "icons/list_group.svg", "html/breadcrumbs": "icons/breadcrumbs.svg",
  "html/pagination": "icons/pagination.svg", "html/progress": "icons/progressbar.svg", "html/navbar": "icons/navbar.svg",
  "html/gridcolumn": "icons/grid_column.svg", "html/gridrow": "icons/grid_row.svg",
  "elements/figure": "icons/image.svg", "elements/font-icon": "icons/star.svg", "elements/svg-image": "icons/star.svg",
  "elements/svg-element": "icons/star.svg", "elements/gallery": "icons/images.svg", "elements/tab": "icons/tabs.svg",
  "elements/tabs": "icons/tabs.svg", "elements/accordion": "icons/accordion.svg", "elements/flip-box": "icons/flipbox.svg",
  "elements/counter": "icons/stopwatch.svg", "elements/testimonial": "icons/testimonial.svg", "elements/social-icons": "icons/social-icons.svg",
  "elements/carousel": "icons/carousel.svg", "elements/slider": "icons/slider.svg", "elements/icon-list": "icons/icon-list.svg",
  "elements/divider": "icons/stopwatch.svg", "elements/separator": "icons/separator.svg", "elements/Image box": "icons/stopwatch.svg",
  "elements/Icon box": "icons/stopwatch.svg", "elements/animated-headline": "icons/dots_three.svg", "elements/price-table": "icons/price-table.svg",
  "elements/price-list": "icons/stopwatch.svg", "elements/reviews": "icons/reviews.svg", "elements/code": "icons/code.svg",
  "elements/image-compare": "icons/image-compare.svg", "elements/rating": "icons/rating.svg",
  "widgets/googlemaps": "icons/map.svg", "widgets/openstreetmap": "icons/map.svg", "widgets/embed-video": "icons/youtube.svg",
  "widgets/facebookcomments": "icons/facebook.svg", "widgets/instagram": "icons/instagram.svg", "widgets/twitter": "icons/twitter.svg",
  "widgets/paypal": "icons/paypal.svg", "widgets/facebookpage": "icons/facebook.svg", "widgets/chartjs": "icons/chart.svg", "widgets/lottie": "icons/lottie.svg",
  "embeds/embed": "icons/code.svg",
  "components/product": "icons/map.svg", "components/products": "icons/products.svg", "components/manufacturers": "icons/categories.svg",
  "components/categories": "icons/categories.svg", "components/search": "icons/search.svg", "components/user": "icons/user.svg",
  "components/product_gallery": "icons/product_gallery.svg", "components/cart": "icons/cart.svg", "components/checkout": "icons/checkout.svg",
  "components/filters": "icons/filters.svg", "components/slider": "icons/slider.svg",
};
