import assert from "node:assert/strict";
import test from "node:test";
import { createHmac } from "node:crypto";
import { handleAdminCampaignsRequest } from "./campaigns-admin.ts";
function token(): string { const enc = (v: unknown) => Buffer.from(JSON.stringify(v)).toString("base64url"); const h = enc({ alg: "HS256", typ: "JWT" }); const p = enc({ sub: "staff_1", email: "staff@example.com", role: "admin", organization_id: "org_1", permissions: ["campaigns:read", "campaigns:write", "campaigns:execute"], exp: Math.floor(Date.now() / 1000) + 300 }); return `${h}.${p}.${createHmac("sha256", "secret").update(`${h}.${p}`).digest("base64url")}`; }
test("campaign CRUD and execution are tenant-scoped, bounded, and replayable", async () => {
  const appStatements: string[] = []; const commerceStatements: string[] = [];
  const app = { query: async <T extends Record<string, unknown>>(text: string, values: readonly unknown[] = []) => { appStatements.push(text); if (text.includes("INSERT INTO public.worker_idempotency_records")) return { rows: [{ state: "pending", request_hash: values[1] }], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("UPDATE public.worker_idempotency_records") || text.startsWith("DELETE FROM public.worker_idempotency_records")) return { rows: [], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("INSERT INTO public.campaigns")) return { rows: [{ id: "c1", name: "Welcome", type: "custom", segment_id: null, subject: "Hello", body_template: "Hi", channel: "email", is_active: true, last_run_at: null, schedule_cron: null, created_at: "2026-09-21T00:00:00.000Z", organization_id: "org_1" }], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("SELECT id,subject")) return { rows: [{ id: "c1", subject: "Hello", body_template: "Hi", execution_key: null, execution_status: "idle" }], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("UPDATE public.campaigns SET execution_key")) return { rows: [{ id: "c1" }], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("INSERT INTO public.background_jobs")) return { rows: [{ id: "job-1" }], rowCount: 1 } as { rows: T[]; rowCount: number }; return { rows: [], rowCount: 0 } as { rows: T[]; rowCount: number }; }, end: async () => {} };
  const commerce = { query: async <T extends Record<string, unknown>>(text: string) => { commerceStatements.push(text); return { rows: [{ code: "SAVE20" }], rowCount: 1 } as { rows: T[]; rowCount: number }; }, end: async () => {} };
  const headers = { Authorization: `Bearer ${token()}`, "Content-Type": "application/json" };
  const created = await handleAdminCampaignsRequest(new Request("https://api.test/api/admin/campaigns", { method: "POST", headers: { ...headers, "Idempotency-Key": "campaign-1" }, body: JSON.stringify({ name: "Welcome", type: "custom" }) }), app, commerce, { CMS_ADMIN_JWT_SECRET: "secret" }); assert.equal(created.status, 201);
  const executed = await handleAdminCampaignsRequest(new Request("https://api.test/api/admin/campaigns/c1/execute", { method: "POST", headers: { ...headers, "Idempotency-Key": "execute-1" } }), app, commerce, { CMS_ADMIN_JWT_SECRET: "secret" }, "c1", true); assert.equal(executed.status, 202); assert.match(appStatements.join("\n"), /organization_id=\$2/); assert.ok(commerceStatements.length > 0);
});
