import type { WorkerDatabaseClient } from "./database.ts";
import { withWorkerTransaction } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";
type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string };
const projection = "id,name,type,segment_id,subject,body_template,channel,is_active,last_run_at,schedule_cron,created_at,organization_id";
const types = new Set(["winback", "birthday", "first_purchase", "upsell", "custom"]);
function json(body: Record<string, unknown>, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function org(claims: WorkerAuthClaims): string | null { const value = claims.organization_id ?? claims.org_id; return typeof value === "string" && value.trim() ? value.trim() : null; }
function allowed(claims: WorkerAuthClaims, permission: string): boolean { const grants = Array.isArray(claims.permissions) ? claims.permissions : []; return claims.role === "owner" || claims.role === "admin" || grants.some((value) => value === "*" || value === permission); }
async function digest(value: unknown): Promise<string> { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))))].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function readBody(request: Request): Promise<Record<string, unknown>> { const length = Number(request.headers.get("content-length") ?? 0); if (length > 128 * 1024) throw new Error("payload_too_large"); const text = await request.text(); if (text.length > 128 * 1024) throw new Error("payload_too_large"); const value = JSON.parse(text) as unknown; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid_payload"); return value as Record<string, unknown>; }
function map(row: Record<string, unknown>): Record<string, unknown> { return { id: String(row.id), name: String(row.name), type: String(row.type), segment_id: row.segment_id == null ? null : String(row.segment_id), subject: row.subject == null ? null : String(row.subject), body_template: row.body_template == null ? null : String(row.body_template), channel: "email", is_active: Boolean(row.is_active), last_run_at: row.last_run_at == null ? null : String(row.last_run_at), schedule_cron: row.schedule_cron == null ? null : String(row.schedule_cron), created_at: String(row.created_at), organization_id: row.organization_id == null ? null : String(row.organization_id) }; }
function validCreate(input: Record<string, unknown>): boolean { return typeof input.name === "string" && input.name.trim().length > 0 && input.name.trim().length <= 160 && typeof input.type === "string" && types.has(input.type) && (input.segment_id === undefined || input.segment_id === null || typeof input.segment_id === "string") && (input.subject === undefined || input.subject === null || typeof input.subject === "string") && (input.body_template === undefined || input.body_template === null || typeof input.body_template === "string" && input.body_template.length <= 100_000) && (input.schedule_cron === undefined || input.schedule_cron === null || typeof input.schedule_cron === "string" && input.schedule_cron.length <= 120); }
function validPatch(input: Record<string, unknown>): boolean { const keys = new Set(["name", "subject", "body_template", "is_active", "schedule_cron", "segment_id"]); return Object.keys(input).length > 0 && Object.keys(input).every((key) => keys.has(key)) && (input.name === undefined || typeof input.name === "string" && input.name.trim().length > 0 && input.name.length <= 160) && (input.subject === undefined || input.subject === null || typeof input.subject === "string" && input.subject.length <= 240) && (input.body_template === undefined || input.body_template === null || typeof input.body_template === "string" && input.body_template.length <= 100_000) && (input.is_active === undefined || typeof input.is_active === "boolean") && (input.schedule_cron === undefined || input.schedule_cron === null || typeof input.schedule_cron === "string" && input.schedule_cron.length <= 120) && (input.segment_id === undefined || input.segment_id === null || typeof input.segment_id === "string"); }
async function promotionGovernance(commerce: WorkerDatabaseClient | undefined, subject: string, template: string): Promise<boolean> { if (!commerce) return false; const result = await commerce.query<{ code: string }>("SELECT DISTINCT upper(trim(code)) AS code FROM public.promotion WHERE deleted_at IS NULL AND trim(code) <> '' ORDER BY code LIMIT 1000"); const codes = new Set(result.rows.map((row) => String(row.code).replaceAll("-", "").toUpperCase())); const mentioned = `${subject}\n${template}`.toUpperCase().match(/\b([A-Z]{2,}\d{2,}|\d{2,}[A-Z]{2,}|[A-Z]{2,}-\d{2,})\b/g) ?? []; return mentioned.every((value) => codes.has(value.replaceAll("-", ""))); }

export async function handleAdminCampaignsRequest(request: Request, app: WorkerDatabaseClient, commerce: WorkerDatabaseClient | undefined, env: Env, campaignId?: string, execute = false): Promise<Response> {
  const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL }); if (!claims) return json({ error: "unauthorized" }, 401); const organizationId = org(claims); if (!organizationId) return json({ error: "organization_claim_required" }, 403);
  if (execute) {
    if (request.method !== "POST" || !campaignId || !allowed(claims, "campaigns:execute")) return json({ error: "forbidden" }, 403); const key = request.headers.get("Idempotency-Key")?.trim(); if (!key) return json({ error: "idempotency_key_required" }, 400); const campaign = await app.query<{ id: string; subject: string | null; body_template: string | null; execution_key: string | null; execution_status: string }>("SELECT id,subject,body_template,execution_key,execution_status FROM public.campaigns WHERE id=$1 AND organization_id=$2 LIMIT 1", [campaignId, organizationId]); if (!campaign.rows[0]) return json({ error: "campaign_not_found" }, 404); const row = campaign.rows[0]; if (row.execution_key === key && row.execution_status === "completed") return json({ sent: 0, replayed: true }); if (!(await promotionGovernance(commerce, row.subject ?? "", row.body_template ?? ""))) return json({ error: "campaign_governance_failed" }, 409); return (await executeIdempotently(new HyperdriveIdempotencyStore(app), `campaign-execute:${organizationId}:${campaignId}:${key}`, await digest({ organizationId, campaignId, key }), async () => { try { const result = await withWorkerTransaction(app, async (transaction) => { const claimed = await transaction.query<{ id: string }>("UPDATE public.campaigns SET execution_key=$1,execution_status='running' WHERE id=$2 AND organization_id=$3 AND execution_status IN ('idle','failed') RETURNING id", [key, campaignId, organizationId]); if (!claimed.rows[0]) return null; const job = await transaction.query<{ id: string }>("INSERT INTO public.background_jobs (job_type,payload,status,progress,created_by) VALUES ('campaign.execute',$1::jsonb,'queued',0,$2) RETURNING id", [JSON.stringify({ campaignId, organizationId, executionKey: key }), typeof claims.email === "string" ? claims.email : claims.sub]); return job.rows[0]?.id ?? null; }); return result ? json({ queued: true, jobId: String(result) }, 202) : json({ error: "campaign_already_executing" }, 409); } catch { return json({ error: "campaign_execution_unavailable" }, 503); } })).response;
  }
  if (request.method === "GET" && !campaignId) { if (!allowed(claims, "campaigns:read")) return json({ error: "forbidden" }, 403); const type = new URL(request.url).searchParams.get("type"); const result = await app.query<Record<string, unknown>>(`SELECT ${projection} FROM public.campaigns WHERE organization_id=$1 ${type && types.has(type) ? "AND type=$2" : ""} ORDER BY created_at DESC LIMIT 500`, type && types.has(type) ? [organizationId, type] : [organizationId]); return json({ data: result.rows.map(map) }); }
  if (request.method === "GET" && campaignId) { if (!allowed(claims, "campaigns:read")) return json({ error: "forbidden" }, 403); const result = await app.query<Record<string, unknown>>(`SELECT ${projection} FROM public.campaigns WHERE id=$1 AND organization_id=$2 LIMIT 1`, [campaignId, organizationId]); return result.rows[0] ? json({ data: map(result.rows[0]) }) : json({ error: "campaign_not_found" }, 404); }
  const write = request.method === "POST" || request.method === "PATCH"; if (!write || !allowed(claims, "campaigns:write")) return json({ error: "method_not_allowed" }, 405); const key = request.headers.get("Idempotency-Key")?.trim(); if (!key) return json({ error: "idempotency_key_required" }, 400); let input: Record<string, unknown>; try { input = await readBody(request); } catch (error) { const large = error instanceof Error && error.message === "payload_too_large"; return json({ error: large ? "payload_too_large" : "invalid_payload" }, large ? 413 : 400); } if (request.method === "POST" ? !validCreate(input) : !validPatch(input)) return json({ error: "invalid_campaign_payload" }, 400); if (input.segment_id) { const segment = await app.query("SELECT id FROM public.customer_segments WHERE id=$1 AND organization_id=$2 LIMIT 1", [input.segment_id, organizationId]); if (!segment.rows[0]) return json({ error: "segment_not_found" }, 404); } return (await executeIdempotently(new HyperdriveIdempotencyStore(app), `campaigns:${organizationId}:${campaignId ?? "collection"}:${key}`, await digest({ organizationId, campaignId, input }), async () => { const result = request.method === "POST" ? await app.query<Record<string, unknown>>(`INSERT INTO public.campaigns (name,type,segment_id,subject,body_template,schedule_cron,channel,organization_id) VALUES ($1,$2,$3,$4,$5,$6,'email',$7) RETURNING ${projection}`, [String(input.name).trim(), input.type, input.segment_id ?? null, input.subject ?? null, input.body_template ?? null, input.schedule_cron ?? null, organizationId]) : await app.query<Record<string, unknown>>(`UPDATE public.campaigns SET name=COALESCE($1,name),subject=CASE WHEN $2::boolean THEN $3::text ELSE subject END,body_template=CASE WHEN $4::boolean THEN $5::text ELSE body_template END,is_active=COALESCE($6,is_active),schedule_cron=CASE WHEN $7::boolean THEN $8::text ELSE schedule_cron END,segment_id=CASE WHEN $9::boolean THEN $10::uuid ELSE segment_id END WHERE id=$11 AND organization_id=$12 RETURNING ${projection}`, [input.name ?? null, input.subject !== undefined, input.subject ?? null, input.body_template !== undefined, input.body_template ?? null, input.is_active ?? null, input.schedule_cron !== undefined, input.schedule_cron ?? null, input.segment_id !== undefined, input.segment_id ?? null, campaignId, organizationId]); return result.rows[0] ? json({ data: map(result.rows[0]) }, request.method === "POST" ? 201 : 200) : json({ error: "campaign_not_found" }, 404); })).response;
}
