import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";
type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string };
type Redirect = { id: string; from_path: string; to_path: string; status_code: 301 | 302 | 307 | 308; active: boolean; preserve_query: boolean; created_at: string };
function json(body: Record<string, unknown>, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function tenant(claims: WorkerAuthClaims): string | null { const value = claims.organization_id ?? claims.org_id; return typeof value === "string" && value.trim() ? value.trim() : null; }
function allowed(claims: WorkerAuthClaims, write: boolean): boolean { const permissions = Array.isArray(claims.permissions) ? claims.permissions : []; const needed = write ? "content:write" : "content:read"; return claims.role === "owner" || claims.role === "admin" || permissions.some((value) => value === "*" || value === needed || (!write && value === "content:write")); }
function normalize(row: Record<string, unknown>): Redirect { const code = Number(row.status_code); return { id: String(row.id ?? ""), from_path: String(row.from_path ?? ""), to_path: String(row.to_path ?? ""), status_code: ([301, 302, 307, 308] as number[]).includes(code) ? code as Redirect["status_code"] : 301, active: Boolean(row.active), preserve_query: Boolean(row.preserve_query), created_at: String(row.created_at ?? "") }; }
function path(value: unknown, allowExternal = false): string | null { if (typeof value !== "string" || !value.trim() || value.length > 2048 || /[\u0000-\u001f\u007f]/.test(value)) return null; const result = value.trim(); if (allowExternal && /^https:\/\//i.test(result)) return result; return result.startsWith("/") && !result.startsWith("//") ? result : null; }
function input(value: unknown): { from: string; to: string; code: number; active: boolean; preserve: boolean } | null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const row = value as Record<string, unknown>; const from = path(row.from_path); const to = path(row.to_path, true); const code = row.status_code === undefined ? 301 : Number(row.status_code); if (!from || !to || ![301, 302, 307, 308].includes(code)) return null; if (row.active !== undefined && typeof row.active !== "boolean") return null; if (row.preserve_query !== undefined && typeof row.preserve_query !== "boolean") return null; return { from, to, code, active: row.active ?? true, preserve: row.preserve_query ?? false }; }
const projection = "id, from_path, to_path, status_code, active, preserve_query, created_at";
async function digest(value: string): Promise<string> { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
function csv(value: string): string { return /[",\n]/.test(value) ? `"${value.replaceAll('"', '""')}"` : value; }
function parseLine(line: string): string[] { const result: string[] = []; let current = ""; let quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"') { if (quoted && line[i + 1] === '"') { current += '"'; i++; } else quoted = !quoted; } else if (char === "," && !quoted) { result.push(current.trim()); current = ""; } else current += char; } result.push(current.trim()); return result; }

export async function handleAdminCmsRedirectsRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  const url = new URL(request.url); const pathname = url.pathname.replace(/^\/api/, ""); const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL }); if (!claims) return json({ error: "unauthorized" }, 401); const organizationId = tenant(claims); if (!organizationId) return json({ error: "organization_claim_required" }, 403);
  const write = request.method !== "GET" || pathname.endsWith("/import"); if (!allowed(claims, write)) return json({ error: "forbidden" }, 403);
  if (pathname.endsWith("/export") && request.method === "GET") { const result = await database.query<Record<string, unknown>>(`SELECT ${projection} FROM public.cms_redirects WHERE organization_id = $1 ORDER BY from_path LIMIT $2`, [organizationId, 5000]); const lines = ["from_path,to_path,status_code,active,preserve_query", ...result.rows.map((value) => { const row = normalize(value); return [csv(row.from_path), csv(row.to_path), row.status_code, row.active ? 1 : 0, row.preserve_query ? 1 : 0].join(","); })]; const body = lines.join("\n"); if (new TextEncoder().encode(body).byteLength > 5 * 1024 * 1024) return json({ error: "export_too_large" }, 413); await database.query("INSERT INTO public.audit_logs (action, resource, details) VALUES ($1,$2,$3::jsonb)", ["cms.redirects.export", "cms_redirects", JSON.stringify({ organization_id: organizationId, count: result.rows.length, actor_subject: claims.sub })]); return new Response(body, { headers: { "Content-Type": "text/csv; charset=utf-8", "Content-Disposition": "attachment; filename=\"cms-redirects.csv\"" } }); }
  if (pathname.endsWith("/resolve") && request.method === "GET") { const target = path(url.searchParams.get("path") ?? "/") ?? "/"; const result = await database.query<Record<string, unknown>>(`SELECT ${projection} FROM public.cms_redirects WHERE organization_id = $1 ORDER BY from_path LIMIT $2`, [organizationId, 5000]); const rows = result.rows.map(normalize); const active = new Map(rows.filter((row) => row.active).map((row) => [row.from_path, row])); const duplicates = [...new Set(rows.map((row) => row.from_path).filter((value, index, all) => all.indexOf(value) !== index))]; const chain: Array<Record<string, unknown>> = []; let current = target; const seen = new Set<string>(); for (let i = 0; i < 16; i++) { if (seen.has(current)) return json({ data: { chain, loop: true, duplicate_from_warnings: duplicates } }); seen.add(current); const row = active.get(current); if (!row) return json({ data: { chain, resolved: false, final_path: current, duplicate_from_warnings: duplicates } }); chain.push({ from_path: row.from_path, to_path: row.to_path, status_code: row.status_code, preserve_query: row.preserve_query }); if (/^https:\/\//i.test(row.to_path)) return json({ data: { chain, resolved: true, final_url: row.to_path, status_code: row.status_code, duplicate_from_warnings: duplicates } }); current = row.to_path; } return json({ data: { chain, loop: true, duplicate_from_warnings: duplicates } }); }
  if (pathname.endsWith("/bulk") && request.method === "PATCH") { const key = request.headers.get("Idempotency-Key")?.trim(); if (!key || key.length > 255) return json({ error: "idempotency_key_required" }, 400); let body: unknown; try { const raw = await request.text(); if (raw.length > 32 * 1024) return json({ error: "payload_too_large" }, 413); body = JSON.parse(raw); } catch { return json({ error: "invalid_json" }, 400); } const bulk = body && typeof body === "object" && !Array.isArray(body) ? body as Record<string, unknown> : null; const ids = bulk && Array.isArray(bulk.ids) ? bulk.ids.filter((id): id is string => typeof id === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)).slice(0, 200) : []; if (!bulk || ids.length !== (Array.isArray(bulk.ids) ? bulk.ids.length : 0) || !ids.length || typeof bulk.active !== "boolean") return json({ error: "invalid_bulk_payload" }, 400); const active = bulk.active; const hash = await digest(JSON.stringify({ organizationId, ids, active })); return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `cms-redirect-bulk:${organizationId}:${key}`, hash, async () => { const result = await database.query(`UPDATE public.cms_redirects SET active = $1 WHERE organization_id = $2 AND id = ANY($3::uuid[])`, [active, organizationId, ids]); await database.query("INSERT INTO public.audit_logs (action, resource, details) VALUES ($1,$2,$3::jsonb)", ["cms.redirects.bulk", "cms_redirects", JSON.stringify({ organization_id: organizationId, actor_subject: claims.sub, updated: result.rowCount ?? 0 })]); return json({ data: { updated: Math.max(0, Math.min(200, result.rowCount ?? 0)) } }); })).response; }
  if (pathname.endsWith("/import") && request.method === "POST") { const key = request.headers.get("Idempotency-Key")?.trim(); if (!key || key.length > 255) return json({ error: "idempotency_key_required" }, 400); let raw: string; try { raw = await request.text(); if (new TextEncoder().encode(raw).byteLength > 1024 * 1024) return json({ error: "payload_too_large" }, 413); } catch { return json({ error: "invalid_body" }, 400); } const lines = raw.split(/\r?\n/).filter((line) => line.trim()); if (lines.length < 2 || lines.length > 1001 || lines.some((line) => line.length > 16_384)) return json({ error: "invalid_csv" }, 400); const header = parseLine(lines[0]).map((value) => value.toLowerCase()); const fromIndex = header.indexOf("from_path"); const toIndex = header.indexOf("to_path"); if (fromIndex < 0 || toIndex < 0) return json({ error: "csv_columns_required" }, 400); const hash = await digest(JSON.stringify({ organizationId, raw })); return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `cms-redirect-import:${organizationId}:${key}`, hash, async () => { const warnings: string[] = []; let imported = 0; for (let index = 1; index < lines.length; index++) { const columns = parseLine(lines[index]); const parsed = input({ from_path: columns[fromIndex], to_path: columns[toIndex], status_code: columns[header.indexOf("status_code")] ? Number(columns[header.indexOf("status_code")]) : 301, active: columns[header.indexOf("active")] ? ["1", "true"].includes(columns[header.indexOf("active")].toLowerCase()) : true, preserve_query: columns[header.indexOf("preserve_query")] ? ["1", "true"].includes(columns[header.indexOf("preserve_query")].toLowerCase()) : false }); if (!parsed) { warnings.push(`Row ${index + 1}: skipped`); continue; } const result = await database.query<Record<string, unknown>>(`INSERT INTO public.cms_redirects (organization_id, from_path, to_path, status_code, active, preserve_query) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (organization_id, from_path) DO UPDATE SET to_path = EXCLUDED.to_path, status_code = EXCLUDED.status_code, active = EXCLUDED.active, preserve_query = EXCLUDED.preserve_query RETURNING ${projection}`, [organizationId, parsed.from, parsed.to, parsed.code, parsed.active, parsed.preserve]); if (result.rows[0]) imported++; else warnings.push(`Row ${index + 1}: could not save`); } await database.query("INSERT INTO public.audit_logs (action, resource, details) VALUES ($1,$2,$3::jsonb)", ["cms.redirects.import", "cms_redirects", JSON.stringify({ organization_id: organizationId, actor_subject: claims.sub, imported, warning_count: warnings.length })]); return json({ data: { imported, warnings: warnings.slice(0, 100) } }); })).response; }
  const idMatch = pathname.match(/^\/admin\/cms\/redirects\/([^/]+)$/); const id = idMatch ? decodeURIComponent(idMatch[1]) : null;
  if (request.method === "GET") { const result = await database.query<Record<string, unknown>>(`SELECT ${projection} FROM public.cms_redirects WHERE organization_id = $1 ORDER BY from_path LIMIT $2`, [organizationId, 5000]); return json({ data: result.rows.map(normalize) }); }
  const key = request.headers.get("Idempotency-Key")?.trim(); if (!key || key.length > 255) return json({ error: "idempotency_key_required" }, 400); let body: unknown; try { const raw = await request.text(); if (raw.length > 32 * 1024) return json({ error: "payload_too_large" }, 413); body = JSON.parse(raw); } catch { return json({ error: "invalid_json" }, 400); }
  if (request.method === "DELETE" && id) { if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)) return json({ error: "invalid_redirect_id" }, 400); const hash = await digest(JSON.stringify({ organizationId, id })); return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `cms-redirect-delete:${organizationId}:${id}:${key}`, hash, async () => { const result = await database.query(`DELETE FROM public.cms_redirects WHERE organization_id = $1 AND id = $2`, [organizationId, id]); if (!result.rowCount) return json({ error: "redirect_not_found" }, 404); await database.query("INSERT INTO public.audit_logs (action, resource, details) VALUES ($1,$2,$3::jsonb)", ["cms.redirect.delete", `cms-redirect:${id}`, JSON.stringify({ organization_id: organizationId, actor_subject: claims.sub })]); return json({ ok: true }); })).response; }
  const parsed = input(body); if (!parsed) return json({ error: "invalid_redirect_payload" }, 400); const hash = await digest(JSON.stringify({ organizationId, id, parsed })); return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `cms-redirect-save:${organizationId}:${id ?? parsed.from}:${key}`, hash, async () => { const result = id ? await database.query<Record<string, unknown>>(`UPDATE public.cms_redirects SET from_path = $2, to_path = $3, status_code = $4, active = $5, preserve_query = $6 WHERE organization_id = $1 AND id = $7 RETURNING ${projection}`, [organizationId, parsed.from, parsed.to, parsed.code, parsed.active, parsed.preserve, id]) : await database.query<Record<string, unknown>>(`INSERT INTO public.cms_redirects (organization_id, from_path, to_path, status_code, active, preserve_query) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (organization_id, from_path) DO UPDATE SET to_path = EXCLUDED.to_path, status_code = EXCLUDED.status_code, active = EXCLUDED.active, preserve_query = EXCLUDED.preserve_query RETURNING ${projection}`, [organizationId, parsed.from, parsed.to, parsed.code, parsed.active, parsed.preserve]); const row = result.rows[0]; if (!row) return json({ error: id ? "redirect_not_found" : "redirect_write_failed" }, id ? 404 : 500); const data = normalize(row); await database.query("INSERT INTO public.audit_logs (action, resource, details) VALUES ($1,$2,$3::jsonb)", [id ? "cms.redirect.update" : "cms.redirect.create", `cms-redirect:${data.id}`, JSON.stringify({ organization_id: organizationId, actor_subject: claims.sub })]); return json({ data }); })).response;
}
