import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";

type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string };
type Row = Record<string, unknown>;
const states = ["pending", "synced", "partial", "failed", "manual_only", "disabled", "stale"];
const modes = ["automatic", "manual", "disabled"];
const supportedApps = [
  ["hubspot", "HubSpot", "crm"], ["salesforce", "Salesforce", "crm"], ["attio", "Attio", "crm"],
  ["pipedrive", "Pipedrive", "sales"], ["close", "Close", "sales"], ["kustomer", "Kustomer", "support"],
  ["intercom", "Intercom", "messaging"], ["zendesk", "Zendesk", "support"], ["zendesk-sell", "Zendesk Sell", "sales"],
  ["zoho-crm", "Zoho CRM", "crm"], ["twenty-crm", "Twenty CRM", "crm"], ["klaviyo", "Klaviyo", "marketing"],
  ["mailchimp", "Mailchimp", "marketing"], ["marketo", "Marketo", "marketing"],
].map(([provider_config_key, label, category]) => ({ provider_config_key, label, category }));
function json(body: Record<string, unknown>, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function obj(v: unknown): Record<string, unknown> { return v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {}; }
function text(v: unknown, max: number): string | null { return typeof v === "string" && v.trim() && v.length <= max ? v.trim() : null; }
function email(v: unknown): string | null { const x = text(v, 320)?.toLowerCase() ?? null; return x && /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(x) ? x : null; }
function org(c: WorkerAuthClaims): string | null { const x = c.organization_id ?? c.org_id; return typeof x === "string" && x.trim() ? x.trim() : null; }
function can(c: WorkerAuthClaims, write: boolean): boolean { const p = Array.isArray(c.permissions) ? c.permissions : []; return c.role === "owner" || c.role === "admin" || p.some((v) => v === "*" || v === (write ? "crm:write" : "crm:read")); }
async function access(r: Request, e: Env, write: boolean): Promise<{ claims: WorkerAuthClaims; organizationId: string } | Response> { const claims = await verifyWorkerBearerToken(r.headers.get("Authorization"), { secret: e.CMS_ADMIN_JWT_SECRET, supabaseUrl: e.SUPABASE_URL }); if (!claims) return json({ error: "unauthorized" }, 401); if (!can(claims, write)) return json({ error: "forbidden" }, 403); const organizationId = org(claims); return organizationId ? { claims, organizationId } : json({ error: "organization_claim_required" }, 403); }
async function body(r: Request): Promise<Record<string, unknown> | Response> { try { const raw = await r.text(); if (raw.length > 256 * 1024) return json({ error: "payload_too_large" }, 413); const value = JSON.parse(raw); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : json({ error: "invalid_payload" }, 400); } catch { return json({ error: "invalid_json" }, 400); } }
function key(r: Request): string | Response { const value = r.headers.get("Idempotency-Key")?.trim(); return value && value.length <= 200 ? value : json({ error: "idempotency_key_required" }, 400); }
async function digest(value: unknown): Promise<string> { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))))].map((x) => x.toString(16).padStart(2, "0")).join(""); }
function metadata(v: unknown): Record<string, unknown> { const x = obj(v); return JSON.stringify(x).length <= 32 * 1024 ? x : {}; }
function row(v: Row, kind: "connection" | "mapping" | "record"): Row {
  const now = new Date().toISOString();
  if (kind === "connection") return { id: String(v.id ?? ""), provider: "nango", provider_config_key: String(v.provider_config_key ?? "nango"), connection_id: String(v.connection_id ?? ""), connection_name: v.connection_name == null ? null : String(v.connection_name), organization_id: v.organization_id == null ? null : String(v.organization_id), branch_id: v.branch_id == null ? null : String(v.branch_id), staff_user_id: v.staff_user_id == null ? null : String(v.staff_user_id), staff_email: v.staff_email == null ? null : String(v.staff_email), sync_scope: ["organization", "branch", "customer"].includes(String(v.sync_scope)) ? v.sync_scope : "global", active: v.active !== false, tags: obj(v.tags), metadata: obj(v.metadata), last_authorized_at: v.last_authorized_at == null ? null : String(v.last_authorized_at), last_synced_at: v.last_synced_at == null ? null : String(v.last_synced_at), last_error: v.last_error == null ? null : String(v.last_error), created_at: String(v.created_at ?? now), updated_at: String(v.updated_at ?? now) };
  if (kind === "mapping") return { id: String(v.id ?? ""), organization_id: v.organization_id == null ? null : String(v.organization_id), customer_email: String(v.customer_email ?? ""), medusa_customer_id: v.medusa_customer_id == null ? null : String(v.medusa_customer_id), provider: "nango", connection_id: v.nango_connection_id == null ? null : String(v.nango_connection_id), external_contact_id: v.nango_external_contact_id == null ? null : String(v.nango_external_contact_id), external_account_id: v.nango_external_account_id == null ? null : String(v.nango_external_account_id), sync_state: states.includes(String(v.sync_state)) ? v.sync_state : "pending", sync_mode: modes.includes(String(v.sync_mode)) ? v.sync_mode : "automatic", capabilities: obj(v.capabilities), metadata: obj(v.metadata), last_error_code: v.last_error_code == null ? null : String(v.last_error_code), last_error: v.last_error == null ? null : String(v.last_error), last_failed_step: v.last_failed_step == null ? null : String(v.last_failed_step), last_synced_at: v.last_synced_at == null ? null : String(v.last_synced_at), last_webhook_event_id: v.last_webhook_event_id == null ? null : String(v.last_webhook_event_id), last_webhook_status: v.last_webhook_status == null ? null : String(v.last_webhook_status), correlation_id: v.correlation_id == null ? null : String(v.correlation_id), idempotency_key: v.idempotency_key == null ? null : String(v.idempotency_key), created_by_email: v.created_by_email == null ? null : String(v.created_by_email), updated_by_email: v.updated_by_email == null ? null : String(v.updated_by_email), created_at: String(v.created_at ?? now), updated_at: String(v.updated_at ?? now) };
  return { id: String(v.id ?? ""), provider: "nango", provider_config_key: String(v.provider_config_key ?? "nango"), connection_id: String(v.connection_id ?? ""), local_entity_type: v.local_entity_type === "deal" ? "deal" : "contact", local_record_id: String(v.local_record_id ?? ""), local_record_label: v.local_record_label == null ? null : String(v.local_record_label), external_entity_type: v.external_entity_type === "deal" ? "deal" : "contact", external_record_id: v.external_record_id == null ? null : String(v.external_record_id), external_account_id: v.external_account_id == null ? null : String(v.external_account_id), sync_state: states.includes(String(v.sync_state)) ? v.sync_state : "pending", sync_mode: modes.includes(String(v.sync_mode)) ? v.sync_mode : "automatic", sync_scope: ["organization", "branch", "customer"].includes(String(v.sync_scope)) ? v.sync_scope : "global", metadata: obj(v.metadata), tags: obj(v.tags), last_error_code: v.last_error_code == null ? null : String(v.last_error_code), last_error: v.last_error == null ? null : String(v.last_error), last_failed_step: v.last_failed_step == null ? null : String(v.last_failed_step), last_synced_at: v.last_synced_at == null ? null : String(v.last_synced_at), last_synced_by_email: v.last_synced_by_email == null ? null : String(v.last_synced_by_email), last_direction: ["to_crm", "from_crm", "bidirectional"].includes(String(v.last_direction)) ? v.last_direction : null, correlation_id: v.correlation_id == null ? null : String(v.correlation_id), created_by_email: v.created_by_email == null ? null : String(v.created_by_email), updated_by_email: v.updated_by_email == null ? null : String(v.updated_by_email), created_at: String(v.created_at ?? now), updated_at: String(v.updated_at ?? now) };
}
async function audit(db: WorkerDatabaseClient, action: string, resource: string, organizationId: string, claims: WorkerAuthClaims): Promise<void> { await db.query("INSERT INTO public.audit_logs (action,resource,details) VALUES ($1,$2,$3::jsonb)", [action, resource, JSON.stringify({ organization_id: organizationId, actor_subject: claims.sub })]); }
export async function handleAdminCrmBridgeRequest(request: Request, db: WorkerDatabaseClient, env: Env): Promise<Response> {
  const auth = await access(request, env, request.method !== "GET"); if (auth instanceof Response) return auth; const { claims, organizationId } = auth;
  if (request.method === "GET") {
    const [connections, mappings, records] = await Promise.all([
      db.query<Row>("SELECT * FROM public.crm_nango_connections WHERE organization_id=$1 ORDER BY updated_at DESC LIMIT 25", [organizationId]),
      db.query<Row>("SELECT * FROM public.crm_nango_mappings WHERE organization_id=$1 ORDER BY updated_at DESC LIMIT 25", [organizationId]),
      db.query<Row>("SELECT r.* FROM public.crm_nango_records r JOIN public.crm_nango_connections c ON c.id=r.connection_row_id WHERE c.organization_id=$1 ORDER BY r.updated_at DESC LIMIT 25", [organizationId]),
    ]);
    const c = connections.rows.map((v) => row(v, "connection")); const m = mappings.rows.map((v) => row(v, "mapping")); const recordsOut = records.rows.map((v) => row(v, "record"));
    return json({ data: { connections: c, mappings: m, records: recordsOut, supportedApps, summary: { connections: c.length, mappings: m.length, records: recordsOut.length } } });
  }
  if (request.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  const idempotency = key(request); if (idempotency instanceof Response) return idempotency; const inputResult = await body(request); if (inputResult instanceof Response) return inputResult; const input = inputResult; const actor = email(claims.email) ?? claims.sub;
  const kind = input.kind; if (kind !== "connection" && kind !== "record" && kind !== "mapping") return json({ error: "kind must be connection, record, or mapping" }, 400);
  const providerConfigKey = text(input.provider_config_key, 128); if (!providerConfigKey) return json({ error: "provider_config_key is required" }, 400);
  const connectionId = text(input.connection_id, 200);
  const requestHash = await digest({ organizationId, input });
  return (await executeIdempotently(new HyperdriveIdempotencyStore(db), `crm-bridge:${organizationId}:${idempotency}`, requestHash, async () => {
    if (kind === "connection") { if (!connectionId) return json({ error: "connection_id is required" }, 400); const result = await db.query<Row>("INSERT INTO public.crm_nango_connections (provider,provider_config_key,connection_id,connection_name,organization_id,branch_id,staff_user_id,staff_email,sync_scope,active,tags,metadata) VALUES ('nango',$1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb) ON CONFLICT (provider,provider_config_key,connection_id) DO UPDATE SET connection_name=EXCLUDED.connection_name,organization_id=EXCLUDED.organization_id,branch_id=EXCLUDED.branch_id,staff_user_id=EXCLUDED.staff_user_id,staff_email=EXCLUDED.staff_email,sync_scope=EXCLUDED.sync_scope,active=EXCLUDED.active,tags=EXCLUDED.tags,metadata=EXCLUDED.metadata,updated_at=now() RETURNING *", [providerConfigKey, connectionId, text(input.connection_name, 200), organizationId, text(input.branch_id, 200), text(input.staff_user_id, 200), email(input.staff_email) ?? actor, text(input.sync_scope, 20) ?? "global", input.active !== false, JSON.stringify(metadata(input.tags)), JSON.stringify(metadata(input.metadata))]); const v = result.rows[0]; if (!v) return json({ error: "crm_write_failed" }, 502); await audit(db, "crm.bridge.connection.upsert", `connection:${v.id}`, organizationId, claims); return json({ data: row(v, "connection") }, 201); }
    if (kind === "mapping") { const customerEmail = email(input.customer_email); if (!customerEmail) return json({ error: "customer_email is required" }, 400); const result = await db.query<Row>("INSERT INTO public.crm_nango_mappings (organization_id,customer_email,medusa_customer_id,nango_provider,nango_connection_id,nango_external_contact_id,nango_external_account_id,sync_state,sync_mode,metadata,created_by_email,updated_by_email) VALUES ($1,$2,$3,'nango',$4,$5,$6,$7,$8,$9::jsonb,$10,$10) ON CONFLICT (organization_id,customer_email,nango_provider,nango_connection_id) DO UPDATE SET medusa_customer_id=EXCLUDED.medusa_customer_id,nango_external_contact_id=EXCLUDED.nango_external_contact_id,nango_external_account_id=EXCLUDED.nango_external_account_id,sync_state=EXCLUDED.sync_state,sync_mode=EXCLUDED.sync_mode,metadata=EXCLUDED.metadata,updated_by_email=EXCLUDED.updated_by_email,updated_at=now() RETURNING *", [organizationId, customerEmail, text(input.medusa_customer_id, 200), connectionId, text(input.external_contact_id, 200), text(input.external_account_id, 200), states.includes(String(input.sync_state)) ? input.sync_state : "pending", modes.includes(String(input.sync_mode)) ? input.sync_mode : "automatic", JSON.stringify(metadata({ customer_name: text(input.customer_name, 320), notes: text(input.notes, 2000) })), actor]); const v = result.rows[0]; if (!v) return json({ error: "crm_write_failed" }, 502); await audit(db, "crm.bridge.mapping.upsert", `mapping:${v.id}`, organizationId, claims); return json({ data: row(v, "mapping") }, 201); }
    if (!connectionId || !text(input.local_record_id, 200) || !["contact", "deal"].includes(String(input.local_entity_type))) return json({ error: "record identity is required" }, 400);
    const connection = await db.query<Row>("SELECT id FROM public.crm_nango_connections WHERE organization_id=$1 AND provider_config_key=$2 AND connection_id=$3 AND active=true LIMIT 1", [organizationId, providerConfigKey, connectionId]); if (!connection.rows[0]) return json({ error: "CRM connection is not available for this organization" }, 403);
    const result = await db.query<Row>("INSERT INTO public.crm_nango_records (connection_row_id,provider,provider_config_key,connection_id,local_entity_type,local_record_id,local_record_label,external_entity_type,external_record_id,external_account_id,sync_state,sync_mode,sync_scope,metadata,last_direction,created_by_email,updated_by_email) VALUES ($1,'nango',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14,$15,$15) ON CONFLICT DO UPDATE SET local_record_label=EXCLUDED.local_record_label,external_record_id=EXCLUDED.external_record_id,external_account_id=EXCLUDED.external_account_id,sync_state=EXCLUDED.sync_state,sync_mode=EXCLUDED.sync_mode,sync_scope=EXCLUDED.sync_scope,metadata=EXCLUDED.metadata,last_direction=EXCLUDED.last_direction,updated_by_email=EXCLUDED.updated_by_email,updated_at=now() RETURNING *", [connection.rows[0].id, providerConfigKey, connectionId, input.local_entity_type, text(input.local_record_id, 200), text(input.local_record_label, 320), input.external_entity_type === "deal" ? "deal" : "contact", text(input.external_record_id, 200), text(input.external_account_id, 200), states.includes(String(input.sync_state)) ? input.sync_state : "pending", modes.includes(String(input.sync_mode)) ? input.sync_mode : "automatic", text(input.sync_scope, 20) ?? "global", JSON.stringify(metadata(input.metadata)), ["to_crm", "from_crm", "bidirectional"].includes(String(input.last_direction)) ? input.last_direction : null, actor]); const v = result.rows[0]; if (!v) return json({ error: "crm_write_failed" }, 502); await audit(db, "crm.bridge.record.upsert", `record:${v.id}`, organizationId, claims); return json({ data: row(v, "record") }, 201);
  })).response;
}
