import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";
import { buildDeliveryLogisticsCoverageMetadata } from "../../../packages/platform-data/src/delivery-logistics-checklist.ts";

type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string; GEOCODING_BASE_URL?: string; OSRM_BASE_URL?: string; PANCAKE_POS_API_KEY?: string; RESEND_API_KEY?: string };
function json(body: Record<string, unknown>, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function org(claims: WorkerAuthClaims): string | null { const value = claims.organization_id ?? claims.org_id; return typeof value === "string" && value.trim() ? value.trim() : null; }
function allowed(claims: WorkerAuthClaims, write: boolean): boolean { const permissions = Array.isArray(claims.permissions) ? claims.permissions : []; const needed = write ? "orders:write" : "dashboard:read"; return claims.role === "owner" || claims.role === "admin" || permissions.some((value) => value === "*" || value === needed); }
function text(value: unknown, max = 255): string | null { return typeof value === "string" && value.trim() ? value.trim().slice(0, max) : null; }
function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
async function digest(value: string): Promise<string> { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function provider(url: URL, timeout: number): Promise<unknown> { const response = await fetch(url, { signal: AbortSignal.timeout(timeout), headers: { accept: "application/json" } }); if (!response.ok) throw new Error("provider_failed"); const raw = await response.text(); if (raw.length > 512 * 1024) throw new Error("provider_response_too_large"); try { return JSON.parse(raw) as unknown; } catch { throw new Error("provider_invalid_response"); } }
function parsedPoint(value: unknown): { latitude: number; longitude: number } | null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const row = value as Record<string, unknown>; return typeof row.latitude === "number" && Number.isFinite(row.latitude) && row.latitude >= -90 && row.latitude <= 90 && typeof row.longitude === "number" && Number.isFinite(row.longitude) && row.longitude >= -180 && row.longitude <= 180 ? { latitude: row.latitude, longitude: row.longitude } : null; }
async function audit(database: WorkerDatabaseClient, action: string, resource: string, tenant: string, subject: string): Promise<void> { await database.query("INSERT INTO public.audit_logs (action, resource, details) VALUES ($1,$2,$3::jsonb)", [action, resource, JSON.stringify({ organization_id: tenant, actor_subject: subject })]); }

export async function handleAdminDeliveryOperationsRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  if (request.method !== "GET" && request.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL }); if (!claims) return json({ error: "unauthorized" }, 401);
  const tenant = org(claims); if (!tenant) return json({ error: "organization_claim_required" }, 403); const pathname = new URL(request.url).pathname.replace(/^\/api/, ""); const write = request.method === "POST"; if (!allowed(claims, write)) return json({ error: "forbidden" }, 403);
  if (request.method === "GET") {
    const [couriers, exceptions, shipments, events, signals] = await Promise.all([
      database.query(`SELECT id, tenant_key, slug, label, phone, status, latitude, longitude, rating, max_weight_kg, max_volume_cm3, cash_balance, cash_limit, metadata, created_at, updated_at FROM public.delivery_logistics_couriers WHERE tenant_key = $1 ORDER BY updated_at DESC LIMIT $2`, [tenant, 200]),
      database.query(`SELECT id, tenant_key, shipment_id, exception_type, severity, details, resolved_at, resolved_by_email, created_by_email, created_at FROM public.delivery_logistics_exceptions WHERE tenant_key = $1 AND resolved_at IS NULL ORDER BY created_at DESC LIMIT $2`, [tenant, 200]),
      database.query(`SELECT id, organization_id, order_id, order_display_id, customer_email, courier_slug, courier_label, status, destination_address, tracking_url, tracking_status, proof_of_delivery, cod_amount, settlement_status, eta_at, last_event_at, created_at, updated_at FROM public.delivery_logistics_shipments WHERE organization_id = $1 ORDER BY updated_at DESC LIMIT $2`, [tenant, 25]),
      database.query(`SELECT id, organization_id, shipment_id, event_type, event_status, event_payload, occurred_at, created_at FROM public.delivery_logistics_events WHERE organization_id = $1 ORDER BY occurred_at DESC LIMIT $2`, [tenant, 25]),
      database.query<{ active_orders: number | string; shipment_due: number | string; recorded_shipments: number | string; tracking_links: number | string; cod_delivered_pending_capture: number | string }>(`SELECT (SELECT count(*) FROM public.payment_attempts WHERE organization_id = $1 AND status IN ('paid', 'paid_awaiting_order', 'finalizing_order')) AS active_orders, (SELECT count(*) FROM public.delivery_logistics_shipments WHERE organization_id = $1 AND status IN ('planned', 'assigned', 'in_transit') AND (eta_at IS NULL OR eta_at <= now())) AS shipment_due, (SELECT count(*) FROM public.delivery_logistics_shipments WHERE organization_id = $1) AS recorded_shipments, (SELECT count(*) FROM public.delivery_logistics_shipments WHERE organization_id = $1 AND tracking_url IS NOT NULL AND trim(tracking_url) <> '') AS tracking_links, (SELECT count(*) FROM public.payment_attempts WHERE organization_id = $1 AND provider = 'cod' AND (provider_payload->>'delivered_at') IS NOT NULL AND (provider_payload->>'cod_capture_complete') IS DISTINCT FROM 'true') AS cod_delivered_pending_capture`, [tenant]),
    ]);
    const coverage = buildDeliveryLogisticsCoverageMetadata();
    const row = signals.rows[0] ?? {};
    const count = (value: unknown): number => Math.max(0, Number(value) || 0);
    return json({ ok: true, overview: {
      coverage: coverage.coverage,
      checklist: coverage.checklist,
      supportedApps: coverage.supportedApps,
      couriers: couriers.rows,
      openExceptions: exceptions.rows,
      shipments: shipments.rows,
      events: events.rows,
      operationalSignals: {
        activeOrders: count(row.active_orders),
        shipmentDue: count(row.shipment_due),
        recordedShipments: count(row.recorded_shipments),
        recentEvents: events.rows.length,
        trackingLinksEnabled: count(row.tracking_links) > 0,
        codDeliveredPendingCapture: count(row.cod_delivered_pending_capture),
        pancakePosConfigured: Boolean(env.PANCAKE_POS_API_KEY?.trim()),
        smsConfigured: Boolean(env.RESEND_API_KEY?.trim()),
      },
    } });
  }
  const key = request.headers.get("Idempotency-Key")?.trim(); if (!key || key.length > 255) return json({ error: "idempotency_key_required" }, 400);
  let body: Record<string, unknown>; try { const raw = await request.text(); if (raw.length > 256 * 1024) return json({ error: "payload_too_large" }, 413); const parsed = JSON.parse(raw) as unknown; if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return json({ error: "invalid_json" }, 400); body = parsed as Record<string, unknown>; } catch { return json({ error: "invalid_json" }, 400); }
  const kind = text(body.kind, 32); if (!kind || !["courier", "telemetry", "proof", "exception", "settlement", "geocode", "route"].includes(kind)) return json({ error: "invalid_operation_kind" }, 400);
  const hash = await digest(JSON.stringify({ tenant, kind, body }));
  return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `delivery-operation:${tenant}:${key}`, hash, async () => {
    if (kind === "geocode") { const address = text(body.address, 500); if (!address) return json({ error: "address_required" }, 400); if (!env.GEOCODING_BASE_URL) return json({ error: "geocoding_not_configured" }, 503); const url = new URL(env.GEOCODING_BASE_URL); url.searchParams.set("q", address); try { const payload = await provider(url, 5000); const root = object(payload); const candidate = Array.isArray(root.results) && root.results[0] ? object(root.results[0]) : root; const point = parsedPoint({ latitude: Number(candidate.latitude), longitude: Number(candidate.longitude) }); if (!point) return json({ error: "geocoding_invalid_response" }, 502); return json({ data: { ...point, label: text(candidate.display_name ?? candidate.label, 500) ?? address } }); } catch { return json({ error: "geocoding_provider_unavailable" }, 503); } }
    if (kind === "route") { const points = Array.isArray(body.points) ? body.points.map(parsedPoint) : []; if (!points.length || points.length > 100 || points.some((point) => !point)) return json({ error: "invalid_route_points" }, 400); if (!env.OSRM_BASE_URL) return json({ error: "routing_not_configured" }, 503); const url = new URL(`${env.OSRM_BASE_URL.replace(/\/$/, "")}/route/v1/driving/${points.map((point) => `${point!.longitude},${point!.latitude}`).join(";")}`); url.searchParams.set("overview", "full"); url.searchParams.set("steps", "true"); try { return json({ data: await provider(url, 8000) }); } catch { return json({ error: "routing_provider_unavailable" }, 503); } }
    const actor = text(claims.email, 320) ?? claims.sub;
    if (kind === "courier") { const slug = text(body.slug, 80); const label = text(body.label, 160); if (!slug || !label) return json({ error: "courier_identity_required" }, 400); const result = await database.query(`INSERT INTO public.delivery_logistics_couriers (tenant_key, slug, label, phone, status, latitude, longitude, rating, max_weight_kg, max_volume_cm3, cash_limit, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) ON CONFLICT (tenant_key,slug) DO UPDATE SET label=EXCLUDED.label, phone=EXCLUDED.phone, status=EXCLUDED.status, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, rating=EXCLUDED.rating, max_weight_kg=EXCLUDED.max_weight_kg, max_volume_cm3=EXCLUDED.max_volume_cm3, cash_limit=EXCLUDED.cash_limit, metadata=EXCLUDED.metadata, updated_at=now() RETURNING id, tenant_key, slug, label, phone, status, latitude, longitude, rating, max_weight_kg, max_volume_cm3, cash_balance, cash_limit, metadata, created_at, updated_at`, [tenant, slug, label, text(body.phone, 40), ["available", "assigned", "offline", "suspended"].includes(String(body.status)) ? body.status : "available", typeof body.latitude === "number" ? body.latitude : null, typeof body.longitude === "number" ? body.longitude : null, typeof body.rating === "number" ? Math.min(5, Math.max(0, body.rating)) : 0, typeof body.max_weight_kg === "number" ? Math.min(10000, Math.max(0, body.max_weight_kg)) : 0, typeof body.max_volume_cm3 === "number" ? Math.min(100000000, Math.max(0, body.max_volume_cm3)) : 0, typeof body.cash_limit === "number" ? Math.min(100000000, Math.max(0, body.cash_limit)) : 10000, JSON.stringify(object(body.metadata))]); await audit(database, "delivery.courier.upsert", `courier:${result.rows[0]?.id ?? slug}`, tenant, actor); return json({ data: result.rows[0] }, 201); }
    const shipmentId = text(body.shipment_id, 160); if (!shipmentId) return json({ error: "shipment_id_required" }, 400);
    if (kind === "telemetry") { const latitude = typeof body.latitude === "number" ? body.latitude : NaN; const longitude = typeof body.longitude === "number" ? body.longitude : NaN; if (!Number.isFinite(latitude) || latitude < -90 || latitude > 90 || !Number.isFinite(longitude) || longitude < -180 || longitude > 180) return json({ error: "invalid_coordinates" }, 400); const result = await database.query(`INSERT INTO public.delivery_logistics_telemetry (tenant_key, shipment_id, courier_id, latitude, longitude, speed_kph, heading, captured_at, idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,COALESCE($8::timestamptz,now()),$9) ON CONFLICT (tenant_key,shipment_id,idempotency_key) DO NOTHING RETURNING id, tenant_key, shipment_id, courier_id, latitude, longitude, speed_kph, heading, captured_at, idempotency_key`, [tenant, shipmentId, text(body.courier_id, 160), latitude, longitude, typeof body.speed_kph === "number" ? Math.min(500, Math.max(0, body.speed_kph)) : null, typeof body.heading === "number" ? Math.min(360, Math.max(0, body.heading)) : null, text(body.captured_at, 64), key]); if (result.rows[0]) await audit(database, "delivery.telemetry.create", `shipment:${shipmentId}`, tenant, actor); return json({ data: result.rows[0] ?? { duplicate: true } }, result.rows[0] ? 201 : 200); }
    if (kind === "proof") { const method = text(body.method, 32); if (!method || !["signature", "photo", "otp", "contactless"].includes(method)) return json({ error: "invalid_proof_method" }, 400); const verified = body.verified === true; if (verified && method === "otp" && (!text(body.otp, 32) || text(body.otp, 32) !== text(body.expected_otp, 32))) return json({ error: "proof_verification_failed" }, 400); const result = await database.query(`INSERT INTO public.delivery_logistics_proofs (tenant_key, shipment_id, method, recipient_name, photo_url, signature, contact_log, otp_digest, latitude, longitude, verified, verified_at, created_by_email) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,CASE WHEN $11 THEN now() ELSE NULL END,$12) RETURNING *`, [tenant, shipmentId, method, text(body.recipient_name, 160), text(body.photo_url, 2048), text(body.signature, 100000), text(body.contact_log, 2000), text(body.otp_digest, 256), typeof body.latitude === "number" ? body.latitude : null, typeof body.longitude === "number" ? body.longitude : null, verified, actor]); if (verified) await database.query(`UPDATE public.delivery_logistics_shipments SET status = 'delivered', proof_of_delivery = $3::jsonb, updated_by_email = $4, updated_at = now() WHERE tenant_key = $1 AND id = $2`, [tenant, shipmentId, JSON.stringify({ proof_id: result.rows[0]?.id, method, verified_at: new Date().toISOString() }), actor]); await audit(database, verified ? "delivery.proof.verify" : "delivery.proof.create", `shipment:${shipmentId}`, tenant, actor); return json({ data: result.rows[0] }, 201); }
    if (kind === "exception") { const exceptionType = text(body.exception_type, 80); const details = text(body.details, 4000); if (!exceptionType || !details) return json({ error: "exception_details_required" }, 400); const result = await database.query(`INSERT INTO public.delivery_logistics_exceptions (tenant_key, shipment_id, exception_type, severity, details, created_by_email) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`, [tenant, shipmentId, exceptionType, ["low", "medium", "high", "critical"].includes(String(body.severity)) ? body.severity : "medium", details, actor]); await audit(database, "delivery.exception.create", `shipment:${shipmentId}`, tenant, actor); return json({ data: result.rows[0] }, 201); }
    if (kind === "settlement") { const result = await database.query(`INSERT INTO public.delivery_logistics_settlements (tenant_key, shipment_id, courier_id, delivery_fee, driver_earnings, tolls, tip, cod_collected, remitted_at, remitted_by_email) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $9 THEN now() ELSE NULL END,CASE WHEN $9 THEN $10 ELSE NULL END) ON CONFLICT (tenant_key,shipment_id) DO UPDATE SET courier_id=EXCLUDED.courier_id, delivery_fee=EXCLUDED.delivery_fee, driver_earnings=EXCLUDED.driver_earnings, tolls=EXCLUDED.tolls, tip=EXCLUDED.tip, cod_collected=EXCLUDED.cod_collected, remitted_at=EXCLUDED.remitted_at, remitted_by_email=EXCLUDED.remitted_by_email RETURNING *`, [tenant, shipmentId, text(body.courier_id, 160), Number(body.delivery_fee) || 0, Math.max(0, (Number(body.delivery_fee) || 0) + (Number(body.tip) || 0) - (Number(body.tolls) || 0)), Number(body.tolls) || 0, Number(body.tip) || 0, Number(body.cod_collected) || 0, body.remitted === true, actor]); await audit(database, "delivery.settlement.upsert", `shipment:${shipmentId}`, tenant, actor); return json({ data: result.rows[0] }, 201); }
    return json({ error: "unsupported_operation" }, 400);
  })).response;
}
