import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";

type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string };
type DeviceType = "terminal" | "printer" | "kds" | "scanner";
type Device = { id: string; name: string; type: DeviceType; ip_address: string | null; is_active: boolean; config: Record<string, unknown>; last_seen_at: string | null; created_at: string };
const projection = "id,name,type,ip_address,is_active,config,last_seen_at,created_at";
function json(body: Record<string, unknown>, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function org(claims: WorkerAuthClaims): string | null { const value = claims.organization_id ?? claims.org_id; return typeof value === "string" && value.trim() ? value.trim() : null; }
function allowed(claims: WorkerAuthClaims): boolean { const permissions = Array.isArray(claims.permissions) ? claims.permissions : []; return claims.role === "owner" || claims.role === "admin" || permissions.some((value) => value === "*" || value === "devices:manage"); }
function mapDevice(value: Device): Record<string, unknown> { return { id: String(value.id), name: String(value.name), type: value.type, ip_address: value.ip_address == null ? null : String(value.ip_address), is_active: Boolean(value.is_active), config: value.config && typeof value.config === "object" && !Array.isArray(value.config) ? value.config : {}, last_seen_at: value.last_seen_at == null ? null : String(value.last_seen_at), created_at: String(value.created_at) }; }
function mergeConfig(previous: Record<string, unknown>, incoming: Record<string, unknown>): Record<string, unknown> { const next = { ...previous, ...incoming }; if (previous.printerTcp && incoming.printerTcp && typeof previous.printerTcp === "object" && typeof incoming.printerTcp === "object" && !Array.isArray(previous.printerTcp) && !Array.isArray(incoming.printerTcp)) next.printerTcp = { ...(previous.printerTcp as Record<string, unknown>), ...(incoming.printerTcp as Record<string, unknown>) }; return next; }
async function readBody(request: Request): Promise<Record<string, unknown>> { const length = Number(request.headers.get("content-length") ?? 0); if (length > 128 * 1024) throw new Error("payload_too_large"); const text = await request.text(); if (text.length > 128 * 1024) throw new Error("payload_too_large"); const value = JSON.parse(text) as unknown; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid_payload"); return value as Record<string, unknown>; }
async function hash(value: unknown): Promise<string> { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))))].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }

export async function handleAdminDevicesRequest(request: Request, database: WorkerDatabaseClient, env: Env, deviceId?: string): Promise<Response> {
  const isCollection = !deviceId;
  if (request.method !== "GET" && !(isCollection && request.method === "POST") && !(deviceId && request.method === "PATCH")) return json({ error: "method_not_allowed" }, 405);
  const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL });
  if (!claims) return json({ error: "unauthorized" }, 401);
  if (!allowed(claims)) return json({ error: "forbidden" }, 403);
  const organizationId = org(claims); if (!organizationId) return json({ error: "organization_claim_required" }, 403);
  if (request.method === "GET") { const result = await database.query<Device>(`SELECT ${projection} FROM public.pos_devices WHERE organization_id=$1 ORDER BY name ASC LIMIT 500`, [organizationId]); return json({ data: result.rows.map(mapDevice) }); }
  const key = request.headers.get("Idempotency-Key")?.trim(); if (!key) return json({ error: "idempotency_key_required" }, 400);
  let body: Record<string, unknown>; try { body = await readBody(request); } catch (error) { const large = error instanceof Error && error.message === "payload_too_large"; return json({ error: large ? "payload_too_large" : "invalid_payload" }, large ? 413 : 400); }
  const config = body.config; if (config !== undefined && (!config || typeof config !== "object" || Array.isArray(config) || Object.keys(config).length > 100)) return json({ error: "invalid_config" }, 400);
  if (request.method === "POST") {
    const name = typeof body.name === "string" ? body.name.trim() : ""; const type = body.type === undefined ? "terminal" : body.type; const ip = body.ip_address === undefined ? null : typeof body.ip_address === "string" ? body.ip_address.trim() : null; if (!name || name.length > 120 || !["terminal", "printer", "kds", "scanner"].includes(String(type)) || (body.ip_address !== undefined && ip === null)) return json({ error: "invalid_device_payload" }, 400);
    const result = await executeIdempotently(new HyperdriveIdempotencyStore(database), `devices:${organizationId}:${key}`, await hash({ organizationId, name, type, ip, config }), async () => { const existing = await database.query<{ id: string; config: Record<string, unknown> }>("SELECT id,config FROM public.pos_devices WHERE organization_id=$1 AND name=$2 LIMIT 1", [organizationId, name]); if (existing.rows[0]) { const updated = await database.query<Device>(`UPDATE public.pos_devices SET type=$1,ip_address=$2,config=$3::jsonb,is_active=true,last_seen_at=now() WHERE id=$4 AND organization_id=$5 RETURNING ${projection}`, [type, ip, JSON.stringify(mergeConfig(existing.rows[0].config ?? {}, (config as Record<string, unknown>) ?? {})), existing.rows[0].id, organizationId]); return updated.rows[0] ? json({ data: mapDevice(updated.rows[0]) }, 201) : json({ error: "device_unavailable" }, 503); } const inserted = await database.query<Device>(`INSERT INTO public.pos_devices (name,type,ip_address,config,organization_id,last_seen_at,is_active) VALUES ($1,$2,$3,$4::jsonb,$5,now(),true) RETURNING ${projection}`, [name, type, ip, JSON.stringify(config ?? {}), organizationId]); return inserted.rows[0] ? json({ data: mapDevice(inserted.rows[0]) }, 201) : json({ error: "device_unavailable" }, 503); }); return result.response;
  }
  const ip = body.ip_address === undefined ? undefined : body.ip_address === null ? null : typeof body.ip_address === "string" ? body.ip_address.trim() : "invalid"; const active = body.is_active; if (ip === "invalid" || (ip !== undefined && typeof ip === "string" && ip.length > 64) || (active !== undefined && typeof active !== "boolean") || (body.config === undefined && ip === undefined && active === undefined)) return json({ error: "invalid_device_payload" }, 400);
  const result = await executeIdempotently(new HyperdriveIdempotencyStore(database), `devices:${organizationId}:${key}`, await hash({ organizationId, deviceId, ip, active, config }), async () => { const current = await database.query<{ config: Record<string, unknown> }>("SELECT config FROM public.pos_devices WHERE id=$1 AND organization_id=$2 LIMIT 1", [deviceId, organizationId]); if (!current.rows[0]) return json({ error: "device_not_found" }, 404); const mergedConfig = body.config === undefined ? null : JSON.stringify(mergeConfig(current.rows[0].config ?? {}, body.config as Record<string, unknown>)); const updated = await database.query<Device>(`UPDATE public.pos_devices SET ip_address=CASE WHEN $1::boolean THEN $2::text ELSE ip_address END,is_active=CASE WHEN $3::boolean THEN $4::boolean ELSE is_active END,config=CASE WHEN $5::boolean THEN $6::jsonb ELSE config END WHERE id=$7 AND organization_id=$8 RETURNING ${projection}`, [ip !== undefined, ip, active !== undefined, active, body.config !== undefined, mergedConfig, deviceId, organizationId]); return updated.rows[0] ? json({ data: mapDevice(updated.rows[0]) }) : json({ error: "device_not_found" }, 404); }); return result.response;
}
