import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";
type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string; ADMIN_STEP_UP_REQUIRED?: string; ADMIN_STEP_UP_SECRET?: string };
const projection = "id,user_id,full_name,email,phone,role,is_active,hired_at,metadata,created_at,updated_at,organization_id";
const roles = new Set(["admin", "manager", "cashier", "staff"]);
function json(body: Record<string, unknown>, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function org(claims: WorkerAuthClaims): string | null { const value = claims.organization_id ?? claims.org_id; return typeof value === "string" && value.trim() ? value.trim() : null; }
function allowed(claims: WorkerAuthClaims, write = false): boolean { const permissions = Array.isArray(claims.permissions) ? claims.permissions : []; const permission = write ? "employees:write" : "employees:read"; return claims.role === "owner" || claims.role === "admin" || permissions.some((value) => value === "*" || value === permission); }
async function readBody(request: Request): Promise<Record<string, unknown>> { const length = Number(request.headers.get("content-length") ?? 0); if (length > 128 * 1024) throw new Error("payload_too_large"); const text = await request.text(); if (text.length > 128 * 1024) throw new Error("payload_too_large"); const value = JSON.parse(text) as unknown; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid_payload"); return value as Record<string, unknown>; }
async function digest(value: unknown): Promise<string> { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))))].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function map(row: Record<string, unknown>): Record<string, unknown> { return { id: String(row.id), user_id: row.user_id == null ? null : String(row.user_id), full_name: String(row.full_name), email: row.email == null ? null : String(row.email), phone: row.phone == null ? null : String(row.phone), role: String(row.role), is_active: Boolean(row.is_active), hired_at: row.hired_at == null ? null : String(row.hired_at), metadata: row.metadata && typeof row.metadata === "object" && !Array.isArray(row.metadata) ? row.metadata : {}, created_at: String(row.created_at), updated_at: String(row.updated_at), organization_id: row.organization_id == null ? null : String(row.organization_id) }; }
function validCommon(input: Record<string, unknown>, create: boolean): boolean { const known = new Set(["full_name", "email", "phone", "role", "hired_at", "user_id", "metadata", "is_active"]); if ([...Object.keys(input)].some((key) => !known.has(key))) return false; const required = typeof input.full_name === "string" && input.full_name.trim().length > 0 && input.full_name.trim().length <= 200; const optional = ["email", "phone", "user_id", "hired_at"].every((key) => input[key] === undefined || typeof input[key] === "string"); const metadata = input.metadata === undefined || (!!input.metadata && typeof input.metadata === "object" && !Array.isArray(input.metadata) && Object.keys(input.metadata).length <= 100); const role = input.role === undefined || (typeof input.role === "string" && roles.has(input.role)); return (create ? required : Object.keys(input).length > 0) && optional && metadata && role && (input.is_active === undefined || typeof input.is_active === "boolean"); }
async function stepUpValid(request: Request, env: Env): Promise<boolean> { if (env.ADMIN_STEP_UP_REQUIRED !== "true") return true; const value = request.headers.get("x-admin-step-up")?.trim() ?? ""; const match = value.match(/^employees\.pin\.write\.(\d+)\.([0-9a-f]+)$/); if (!match || !env.ADMIN_STEP_UP_SECRET) return false; const expires = Number(match[1]); if (!Number.isInteger(expires) || expires < Math.floor(Date.now() / 1000)) return false; const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(env.ADMIN_STEP_UP_SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const expected = [...new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(`employees.pin.write.${expires}`)))].map((byte) => byte.toString(16).padStart(2, "0")).join(""); return expected === match[2]; }
function pinHash(pin: string, salt: string): Promise<string> { return crypto.subtle.digest("SHA-256", new TextEncoder().encode(salt + pin)).then((value) => [...new Uint8Array(value)].map((byte) => byte.toString(16).padStart(2, "0")).join("")); }
async function createPinHash(pin: string): Promise<string> { const bytes = new Uint8Array(16); crypto.getRandomValues(bytes); const salt = [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join(""); return `${salt}:${await pinHash(pin, salt)}`; }
async function verifyHash(pin: string, stored: string): Promise<boolean> { const parts = stored.split(":"); if (parts.length !== 2 || !/^[0-9a-f]{32}$/.test(parts[0]) || !/^[0-9a-f]{64}$/.test(parts[1])) return false; const actual = await pinHash(pin, parts[0]); let diff = 0; for (let index = 0; index < actual.length; index += 1) diff |= actual.charCodeAt(index) ^ parts[1].charCodeAt(index); return diff === 0; }

export async function handleAdminEmployeesRequest(request: Request, database: WorkerDatabaseClient, env: Env, employeeId?: string): Promise<Response> {
  const isCollection = !employeeId; const read = request.method === "GET"; const mutation = request.method === "POST" || request.method === "PATCH" || request.method === "DELETE";
  if ((!isCollection && request.method !== "GET" && request.method !== "PATCH" && request.method !== "DELETE") || (isCollection && request.method !== "GET" && request.method !== "POST")) return json({ error: "method_not_allowed" }, 405);
  const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL }); if (!claims) return json({ error: "unauthorized" }, 401); if (!allowed(claims, !read)) return json({ error: "forbidden" }, 403); const organizationId = org(claims); if (!organizationId) return json({ error: "organization_claim_required" }, 403);
  if (read) { const active = new URL(request.url).searchParams.get("active") === "true"; const result = await database.query<Record<string, unknown>>(`SELECT ${projection} FROM public.employees WHERE organization_id=$1 ${active ? "AND is_active=true" : ""} ORDER BY created_at DESC LIMIT 500`, [organizationId]); return json(isCollection ? { data: result.rows.map(map) } : result.rows[0] ? { data: map(result.rows[0]) } : { error: "employee_not_found" }, result.rows[0] || isCollection ? 200 : 404); }
  const key = request.headers.get("Idempotency-Key")?.trim(); if (!key) return json({ error: "idempotency_key_required" }, 400);
  if (request.method === "DELETE") return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `employees:${organizationId}:${employeeId}:${key}`, await digest({ organizationId, employeeId, method: "DELETE" }), async () => { const result = await database.query("DELETE FROM public.employees WHERE id=$1 AND organization_id=$2", [employeeId, organizationId]); return result.rowCount ? json({ success: true }) : json({ error: "employee_not_found" }, 404); })).response;
  let input: Record<string, unknown>; try { input = await readBody(request); } catch (error) { const large = error instanceof Error && error.message === "payload_too_large"; return json({ error: large ? "payload_too_large" : "invalid_payload" }, large ? 413 : 400); }
  if (!validCommon(input, request.method === "POST")) return json({ error: "invalid_employee_payload" }, 400);
  const values = [typeof input.full_name === "string" ? input.full_name.trim() : null, input.email === undefined ? null : input.email, input.phone === undefined ? null : input.phone, input.role ?? "staff", input.hired_at ?? null, input.user_id ?? null, JSON.stringify(input.metadata ?? {}), input.is_active ?? true, organizationId];
  return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `employees:${organizationId}:${employeeId ?? "collection"}:${key}`, await digest({ organizationId, employeeId, input }), async () => { const result = request.method === "POST" ? await database.query<Record<string, unknown>>(`INSERT INTO public.employees (full_name,email,phone,role,hired_at,user_id,metadata,is_active,organization_id) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9) RETURNING ${projection}`, values) : await database.query<Record<string, unknown>>(`UPDATE public.employees SET full_name=COALESCE($1,full_name),email=CASE WHEN $2::boolean THEN $3::text ELSE email END,phone=CASE WHEN $4::boolean THEN $5::text ELSE phone END,role=COALESCE($6,role),hired_at=CASE WHEN $7::boolean THEN $8::timestamptz ELSE hired_at END,user_id=CASE WHEN $9::boolean THEN $10::text ELSE user_id END,metadata=CASE WHEN $11::boolean THEN $12::jsonb ELSE metadata END,is_active=COALESCE($13,is_active),updated_at=now() WHERE id=$14 AND organization_id=$15 RETURNING ${projection}`, [input.full_name === undefined ? null : String(input.full_name).trim(), input.email !== undefined, input.email ?? null, input.phone !== undefined, input.phone ?? null, input.role ?? null, input.hired_at !== undefined, input.hired_at ?? null, input.user_id !== undefined, input.user_id ?? null, input.metadata !== undefined, JSON.stringify(input.metadata ?? {}), input.is_active ?? null, employeeId, organizationId]); return result.rows[0] ? json({ data: map(result.rows[0]) }, request.method === "POST" ? 201 : 200) : json({ error: request.method === "POST" ? "employee_unavailable" : "employee_not_found" }, request.method === "POST" ? 503 : 404); })).response;
}

export async function handleAdminEmployeePinRequest(request: Request, database: WorkerDatabaseClient, env: Env, employeeId: string): Promise<Response> {
  if (request.method !== "PUT" && request.method !== "POST") return json({ error: "method_not_allowed" }, 405); const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL }); if (!claims) return json({ error: "unauthorized" }, 401); const write = request.method === "PUT"; if (!allowed(claims, write)) return json({ error: "forbidden" }, 403); if (write && !(await stepUpValid(request, env))) return json({ error: "step_up_required" }, 403); const organizationId = org(claims); if (!organizationId) return json({ error: "organization_claim_required" }, 403); let input: Record<string, unknown>; try { input = await readBody(request); } catch { return json({ error: "invalid_payload" }, 400); } const pin = typeof input.pin === "string" ? input.pin : ""; if (!/^\d{4,8}$/.test(pin)) return json({ error: "invalid_pin" }, 400); if (!write) { const result = await database.query<{ pin_hash: string | null }>("SELECT pin_hash FROM public.employees WHERE id=$1 AND organization_id=$2 LIMIT 1", [employeeId, organizationId]); return json({ valid: Boolean(result.rows[0]?.pin_hash && await verifyHash(pin, result.rows[0].pin_hash)) }); } const key = request.headers.get("Idempotency-Key")?.trim(); if (!key) return json({ error: "idempotency_key_required" }, 400); const hash = await createPinHash(pin); return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `employee-pin:${organizationId}:${employeeId}:${key}`, await digest({ organizationId, employeeId, pin }), async () => { const result = await database.query("UPDATE public.employees SET pin_hash=$1,updated_at=now() WHERE id=$2 AND organization_id=$3", [hash, employeeId, organizationId]); return result.rowCount ? json({ success: true }) : json({ error: "employee_not_found" }, 404); })).response; }
