import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { withWorkerTransaction, type WorkerDatabaseClient } from "./database.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";

type Env = { JWT_SECRET?: string; SUPABASE_URL?: string };
type Line = { id: string; purchase_order_id: string; product_id: string; variant_id: string; ordered_quantity: number; received_quantity: number; unit_cost_minor: number; created_at: string };
type Row = Record<string, unknown> & { id: string; organization_id: string; status: string; revision: number; destination_location_id: string; inventory_purchase_order_lines?: Line[] };
const json = (body: Record<string, unknown>, status = 200) => Response.json(body, { status, headers: { "Cache-Control": "no-store" } });
const org = (c: WorkerAuthClaims) => typeof (c.organization_id ?? c.org_id) === "string" && String(c.organization_id ?? c.org_id).trim() ? String(c.organization_id ?? c.org_id).trim() : null;
const can = (c: WorkerAuthClaims, p: "read" | "write") => c.role === "owner" || c.role === "admin" || (Array.isArray(c.permissions) && c.permissions.some((v) => v === "*" || v === `inventory:${p}`));
const uuid = (v: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
async function auth(request: Request, env: Env): Promise<WorkerAuthClaims | Response> { return await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.JWT_SECRET, supabaseUrl: env.SUPABASE_URL }) ?? json({ error: "unauthorized" }, 401); }
async function digest(value: unknown): Promise<string> { const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))); return Array.from(new Uint8Array(d), (v) => v.toString(16).padStart(2, "0")).join(""); }
function key(request: Request): string | null { const v = request.headers.get("Idempotency-Key")?.trim(); return v && v.length >= 8 && v.length <= 255 ? v : null; }
async function parse(request: Request, max: number): Promise<Record<string, unknown> | Response> { const raw = await request.text(); if (new TextEncoder().encode(raw).byteLength > max) return json({ error: "payload_too_large" }, 413); try { const v = JSON.parse(raw); return v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : json({ error: "invalid_json" }, 400); } catch { return json({ error: "invalid_json" }, 400); } }
function create(value: Record<string, unknown>): { supplier: string; destination: string; lines: Array<{ product: string; variant: string; ordered: number; cost: number }> } | null {
  if (Object.keys(value).some((k) => !["supplierName", "destinationLocationId", "currencyCode", "lines"].includes(k)) || value.currencyCode !== undefined && value.currencyCode !== "PHP") return null;
  const supplier = typeof value.supplierName === "string" ? value.supplierName.trim() : ""; const destination = typeof value.destinationLocationId === "string" ? value.destinationLocationId.trim() : ""; const raw = value.lines;
  if (!supplier || supplier.length > 200 || !destination || destination.length > 200 || !Array.isArray(raw) || raw.length < 1 || raw.length > 100) return null;
  const seen = new Set<string>(); const lines: Array<{ product: string; variant: string; ordered: number; cost: number }> = [];
  for (const item of raw) { if (!item || typeof item !== "object" || Array.isArray(item)) return null; const v = item as Record<string, unknown>; if (Object.keys(v).some((k) => !["productId", "variantId", "orderedQuantity", "unitCostMinor"].includes(k))) return null; const product = typeof v.productId === "string" ? v.productId.trim() : ""; const variant = typeof v.variantId === "string" ? v.variantId.trim() : ""; if (!product || !variant || seen.has(variant) || !Number.isSafeInteger(v.orderedQuantity) || Number(v.orderedQuantity) <= 0 || Number(v.orderedQuantity) > 1_000_000 || !Number.isSafeInteger(v.unitCostMinor) || Number(v.unitCostMinor) < 0 || Number(v.unitCostMinor) > 1_000_000_000) return null; seen.add(variant); lines.push({ product, variant, ordered: Number(v.orderedQuantity), cost: Number(v.unitCostMinor) }); }
  return { supplier, destination, lines };
}
function operation(value: Record<string, unknown>): { action: "submit" | "receive" | "cancel"; revision: number; lines: Array<{ id: string; quantity: number }> } | null {
  if (Object.keys(value).some((k) => !["action", "expectedRevision", "lines"].includes(k)) || !["submit", "receive", "cancel"].includes(value.action as string) || !Number.isSafeInteger(value.expectedRevision) || Number(value.expectedRevision) < 1) return null;
  const raw = value.lines; if (raw !== undefined && (!Array.isArray(raw) || raw.length > 100)) return null; const lines: Array<{ id: string; quantity: number }> = []; const seen = new Set<string>();
  for (const item of (Array.isArray(raw) ? raw : [])) { if (!item || typeof item !== "object" || Array.isArray(item)) return null; const v = item as Record<string, unknown>; const id = typeof v.lineId === "string" ? v.lineId.trim() : ""; if (!uuid(id) || !Number.isSafeInteger(v.quantity) || Number(v.quantity) <= 0 || Number(v.quantity) > 1_000_000 || seen.has(id)) return null; seen.add(id); lines.push({ id, quantity: Number(v.quantity) }); }
  if (value.action === "receive" && lines.length === 0 || value.action !== "receive" && lines.length > 0) return null; return { action: value.action as "submit" | "receive" | "cancel", revision: Number(value.expectedRevision), lines };
}
async function load(db: WorkerDatabaseClient, organization: string, id?: string, limit = 50): Promise<Row[]> { const q = id ? [`SELECT p.*,COALESCE((SELECT json_agg(l ORDER BY l.created_at) FROM public.inventory_purchase_order_lines l WHERE l.purchase_order_id=p.id),'[]'::json) AS inventory_purchase_order_lines FROM public.inventory_purchase_orders p WHERE p.organization_id=$1 AND p.id=$2 LIMIT 1`, [organization, id]] as const : [`SELECT p.*,COALESCE((SELECT json_agg(l ORDER BY l.created_at) FROM public.inventory_purchase_order_lines l WHERE l.purchase_order_id=p.id),'[]'::json) AS inventory_purchase_order_lines FROM public.inventory_purchase_orders p WHERE p.organization_id=$1 ORDER BY p.created_at DESC LIMIT $2`, [organization, limit]] as const; const result = await db.query<Row>(q[0], q[1]); return result.rows.map((r) => ({ ...r, inventory_purchase_order_lines: Array.isArray(r.inventory_purchase_order_lines) ? r.inventory_purchase_order_lines : [] })); }
async function audit(db: WorkerDatabaseClient, action: string, id: string, organization: string, subject: string, details: Record<string, unknown>) { await db.query("INSERT INTO public.audit_logs (action,resource,details) VALUES ($1,$2,$3::jsonb)", [action, `inventory_purchase_order:${id}`, JSON.stringify({ organization_id: organization, actor_subject: subject, ...details })]); }

export async function handleInventoryPurchaseOrderCollectionRequest(request: Request, app: WorkerDatabaseClient, commerce: WorkerDatabaseClient | undefined, env: Env): Promise<Response> {
  if (!["GET", "POST"].includes(request.method)) return json({ error: "method_not_allowed" }, 405); const c = await auth(request, env); if (c instanceof Response) return c; const organization = org(c); if (!organization) return json({ error: "organization_scope_required" }, 403);
  if (request.method === "GET") { if (!can(c, "read")) return json({ error: "forbidden" }, 403); const n = Number(new URL(request.url).searchParams.get("limit") ?? "50"); return json({ data: await load(app, organization, undefined, Number.isSafeInteger(n) && n > 0 ? Math.min(200, n) : 50), organizationId: organization }); }
  if (!can(c, "write")) return json({ error: "forbidden" }, 403); const idempotency = key(request); if (!idempotency) return json({ error: "idempotency_key_required" }, 400); const raw = await parse(request, 128 * 1024); if (raw instanceof Response) return raw; const input = create(raw); if (!input) return json({ error: "invalid_purchase_order_payload" }, 400); const requestHash = await digest({ organization, ...input }); const scoped = await digest(`inventory-purchase-order:create:${organization}:${idempotency}`);
  return (await executeIdempotently(new HyperdriveIdempotencyStore(app), scoped, requestHash, async () => { const made = await withWorkerTransaction(app, async (tx) => { const inserted = await tx.query<Row>(`INSERT INTO public.inventory_purchase_orders (organization_id,supplier_name,destination_location_id,currency_code,idempotency_key,created_by_email) VALUES ($1,$2,$3,'PHP',$4,$5) RETURNING *`, [organization, input.supplier, input.destination, idempotency, typeof c.email === "string" ? c.email : c.sub]); const po = inserted.rows[0]; if (!po) throw new Error("purchase_order_create_failed"); for (const line of input.lines) await tx.query(`INSERT INTO public.inventory_purchase_order_lines (purchase_order_id,product_id,variant_id,ordered_quantity,unit_cost_minor) VALUES ($1,$2,$3,$4,$5)`, [po.id, line.product, line.variant, line.ordered, line.cost]); await audit(tx, "inventory.purchase_order.create", po.id, organization, c.sub, { lines: input.lines.length }); return (await load(tx, organization, po.id))[0]; }); return json({ data: made }, 201); })).response;
}

export async function handleInventoryPurchaseOrderDetailRequest(request: Request, app: WorkerDatabaseClient, env: Env, id: string): Promise<Response> { if (request.method !== "GET") return json({ error: "method_not_allowed" }, 405); if (!uuid(id)) return json({ error: "invalid_purchase_order_id" }, 400); const c = await auth(request, env); if (c instanceof Response) return c; const organization = org(c); if (!organization) return json({ error: "organization_scope_required" }, 403); if (!can(c, "read")) return json({ error: "forbidden" }, 403); const found = await load(app, organization, id); return found[0] ? json({ data: found[0] }) : json({ error: "purchase_order_not_found" }, 404); }

export async function handleInventoryPurchaseOrderMutationRequest(request: Request, app: WorkerDatabaseClient, commerce: WorkerDatabaseClient | undefined, env: Env, id: string): Promise<Response> {
  if (request.method !== "POST") return json({ error: "method_not_allowed" }, 405); if (!uuid(id)) return json({ error: "invalid_purchase_order_id" }, 400); const c = await auth(request, env); if (c instanceof Response) return c; const organization = org(c); if (!organization) return json({ error: "organization_scope_required" }, 403); if (!can(c, "write")) return json({ error: "forbidden" }, 403); const idempotency = key(request); if (!idempotency) return json({ error: "idempotency_key_required" }, 400); const raw = await parse(request, 64 * 1024); if (raw instanceof Response) return raw; const input = operation(raw); if (!input) return json({ error: "invalid_purchase_order_operation" }, 400); const scoped = await digest(`inventory-purchase-order:${organization}:${id}:${input.action}:${idempotency}`); const requestHash = await digest({ organization, id, ...input });
  return (await executeIdempotently(new HyperdriveIdempotencyStore(app), scoped, requestHash, async () => { const found = (await load(app, organization, id))[0]; if (!found) return json({ error: "purchase_order_not_found" }, 404); if (found.revision !== input.revision) return json({ error: "purchase_order_conflict", code: "INVENTORY_PURCHASE_ORDER_CONFLICT" }, 409); const allowed: Record<string, string[]> = { submit: ["draft"], cancel: ["draft", "submitted", "partially_received"], receive: ["submitted", "partially_received"] }; if (!allowed[input.action].includes(found.status)) return json({ error: "purchase_order_invalid_state", code: "INVENTORY_PURCHASE_ORDER_INVALID_STATE" }, 409);
    if (input.action !== "receive") { const next = input.action === "submit" ? "submitted" : "cancelled"; const updated = await withWorkerTransaction(app, async (tx) => { const result = await tx.query<Row>(`UPDATE public.inventory_purchase_orders SET status=$1,revision=revision+1,updated_at=now() WHERE id=$2 AND organization_id=$3 AND revision=$4 RETURNING *`, [next, id, organization, input.revision]); if (!result.rows[0]) throw new Error("purchase_order_conflict"); await audit(tx, `inventory.purchase_order.${input.action}`, id, organization, c.sub, { status: next }); return (await load(tx, organization, id))[0]; }); return json({ data: updated }); }
    if (!commerce) return json({ error: "commerce_database_unavailable" }, 503); const lines = found.inventory_purchase_order_lines ?? []; const incoming = new Map(input.lines.map((v) => [v.id, v.quantity])); const updates = lines.filter((l) => incoming.has(l.id)).map((l) => ({ line: l, quantity: incoming.get(l.id)! })); if (!updates.length || updates.some((v) => v.line.received_quantity + v.quantity > v.line.ordered_quantity)) return json({ error: "received_quantity_invalid", code: "INVENTORY_RECEIPT_QUANTITY_INVALID" }, 400);
    await withWorkerTransaction(app, async (tx) => { const r = await tx.query(`UPDATE public.inventory_purchase_orders SET status='receiving',revision=revision+1,updated_at=now() WHERE id=$1 AND organization_id=$2 AND revision=$3`, [id, organization, input.revision]); if (!r.rowCount) throw new Error("purchase_order_conflict"); });
    try { await withWorkerTransaction(commerce, async (tx) => { for (const { line, quantity } of updates) { const stock = await tx.query<{ inventory_item_id: string; stocked_quantity: number | string; reserved_quantity: number | string }>(`SELECT pvi.inventory_item_id,il.stocked_quantity,il.reserved_quantity FROM public.product_variant_inventory_item pvi JOIN public.product_variant v ON v.id=pvi.variant_id AND v.deleted_at IS NULL JOIN public.product p ON p.id=v.product_id AND p.deleted_at IS NULL JOIN public.inventory_level il ON il.inventory_item_id=pvi.inventory_item_id AND il.location_id=$2 AND il.deleted_at IS NULL WHERE v.id=$1 AND v.product_id=$3 AND p.metadata->>'organization_id'=$4 FOR UPDATE`, [line.variant_id, found.destination_location_id, line.product_id, organization]); const s = stock.rows[0]; if (!s) throw new Error("inventory_variant_not_found"); const next = Number(s.stocked_quantity) + quantity; if (next < Number(s.reserved_quantity) || next > 1_000_000) throw new Error("inventory_quantity_invalid"); await tx.query(`UPDATE public.inventory_level SET stocked_quantity=$1,updated_at=now() WHERE inventory_item_id=$2 AND location_id=$3`, [next, s.inventory_item_id, found.destination_location_id]); } }); } catch { await app.query(`UPDATE public.inventory_purchase_orders SET status='receive_failed',failure_code='INVENTORY_RECEIPT_FAILED',failure_message='Unable to apply inventory receipt',revision=revision+1,updated_at=now() WHERE id=$1 AND organization_id=$2 AND status='receiving'`, [id, organization]); return json({ error: "Unable to apply inventory receipt", code: "INVENTORY_RECEIPT_FAILED" }, 409); }
    const all = lines.every((l) => l.received_quantity + (incoming.get(l.id) ?? 0) === l.ordered_quantity); const completed = await withWorkerTransaction(app, async (tx) => { for (const { line, quantity } of updates) { const r = await tx.query(`UPDATE public.inventory_purchase_order_lines SET received_quantity=received_quantity+$1 WHERE id=$2 AND purchase_order_id=$3 AND received_quantity=$4`, [quantity, line.id, id, line.received_quantity]); if (!r.rowCount) throw new Error("purchase_order_line_conflict"); } const result = await tx.query<Row>(`UPDATE public.inventory_purchase_orders SET status=$1,revision=revision+1,updated_at=now() WHERE id=$2 AND organization_id=$3 AND status='receiving' RETURNING *`, [all ? "received" : "partially_received", id, organization]); if (!result.rows[0]) throw new Error("purchase_order_finalize_failed"); await audit(tx, "inventory.purchase_order.receive", id, organization, c.sub, { lines: updates.length }); return (await load(tx, organization, id))[0]; }); return json({ data: completed });
  })).response;
}
