import assert from "node:assert/strict";
import test from "node:test";
import { createHmac } from "node:crypto";
import type { WorkerDatabaseClient } from "./database.ts";
import { handleInventoryTransferCollectionRequest, handleInventoryTransferDetailRequest } from "./inventory-transfers-admin.ts";
function token(claims: Record<string, unknown> = {}) { const e = (v: unknown) => Buffer.from(JSON.stringify(v)).toString("base64url"); const h = e({ alg: "HS256", typ: "JWT" }); const p = e({ sub: "staff-1", exp: Math.floor(Date.now() / 1000) + 300, organization_id: "org-a", permissions: ["inventory:read"], ...claims }); return `${h}.${p}.${createHmac("sha256", "test-secret").update(`${h}.${p}`).digest("base64url")}`; }
const id = "8c4b85ee-4a78-4b9f-a41f-15a69df3221a";
test("transfer reads are tenant-scoped and bounded", async () => { const db = { query: async <T extends Record<string, unknown>>() => ({ rows: [{ id, organization_id: "org-a", status: "draft", revision: 1, source_location_id: "loc-a", destination_location_id: "loc-b", inventory_transfer_lines: [] }] as T[], rowCount: 1 }), end: async () => {} } as WorkerDatabaseClient; const response = await handleInventoryTransferCollectionRequest(new Request("https://worker.test/api/admin/inventory/transfers?limit=999", { headers: { Authorization: `Bearer ${token()}` } }), db, undefined, { JWT_SECRET: "test-secret" }); assert.equal(response.status, 200); assert.equal((await response.json() as { organizationId: string }).organizationId, "org-a"); });
test("transfer detail denies unauthorized staff before database access", async () => { const db = { query: async () => { throw new Error("database must not be reached"); }, end: async () => {} } as unknown as WorkerDatabaseClient; const response = await handleInventoryTransferDetailRequest(new Request(`https://worker.test/api/admin/inventory/transfers/${id}`, { headers: { Authorization: `Bearer ${token({ permissions: ["content:read"] })}` } }), db, { JWT_SECRET: "test-secret" }, id); assert.equal(response.status, 403); });
