import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { withWorkerTransaction, type WorkerDatabaseClient } from "./database.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";

type Env = { JWT_SECRET?: string; SUPABASE_URL?: string };
type Line = { id: string; transfer_id: string; product_id: string; variant_id: string; quantity: number; created_at: string };
type Row = Record<string, unknown> & { id: string; organization_id: string; status: string; revision: number; source_location_id: string; destination_location_id: string; inventory_transfer_lines?: Line[] };
const json = (body: Record<string, unknown>, status = 200) => Response.json(body, { status, headers: { "Cache-Control": "no-store" } });
const org = (c: WorkerAuthClaims) => { const v = c.organization_id ?? c.org_id; return typeof v === "string" && v.trim() ? v.trim() : null; };
const can = (c: WorkerAuthClaims, p: "read" | "write") => c.role === "owner" || c.role === "admin" || (Array.isArray(c.permissions) && c.permissions.some((v) => v === "*" || v === `inventory:${p}`));
const uuid = (v: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
async function auth(r: Request, e: Env): Promise<WorkerAuthClaims | Response> { return await verifyWorkerBearerToken(r.headers.get("Authorization"), { secret: e.JWT_SECRET, supabaseUrl: e.SUPABASE_URL }) ?? json({ error: "unauthorized" }, 401); }
async function hash(v: unknown) { const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(v))); return Array.from(new Uint8Array(d), (b) => b.toString(16).padStart(2, "0")).join(""); }
function key(r: Request) { const v = r.headers.get("Idempotency-Key")?.trim(); return v && v.length >= 8 && v.length <= 255 ? v : null; }
async function parse(r: Request, max: number): Promise<Record<string, unknown> | Response> { const raw = await r.text(); if (new TextEncoder().encode(raw).byteLength > max) return json({ error: "payload_too_large" }, 413); try { const v = JSON.parse(raw); return v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : json({ error: "invalid_json" }, 400); } catch { return json({ error: "invalid_json" }, 400); } }
function create(v: Record<string, unknown>) { if (Object.keys(v).some((k) => !["sourceLocationId", "destinationLocationId", "lines"].includes(k))) return null; const source = typeof v.sourceLocationId === "string" ? v.sourceLocationId.trim() : ""; const destination = typeof v.destinationLocationId === "string" ? v.destinationLocationId.trim() : ""; if (!source || !destination || source === destination || source.length > 200 || destination.length > 200 || !Array.isArray(v.lines) || v.lines.length < 1 || v.lines.length > 100) return null; const seen = new Set<string>(); const lines: Array<{ product: string; variant: string; quantity: number }> = []; for (const item of v.lines) { if (!item || typeof item !== "object" || Array.isArray(item)) return null; const x = item as Record<string, unknown>; const product = typeof x.productId === "string" ? x.productId.trim() : ""; const variant = typeof x.variantId === "string" ? x.variantId.trim() : ""; if (!product || !variant || seen.has(variant) || !Number.isSafeInteger(x.quantity) || Number(x.quantity) <= 0 || Number(x.quantity) > 1_000_000) return null; seen.add(variant); lines.push({ product, variant, quantity: Number(x.quantity) }); } return { source, destination, lines }; }
function operation(v: Record<string, unknown>) { if (Object.keys(v).some((k) => !["action", "expectedRevision"].includes(k)) || !["approve", "ship", "complete", "cancel"].includes(v.action as string) || !Number.isSafeInteger(v.expectedRevision) || Number(v.expectedRevision) < 1) return null; return { action: v.action as "approve" | "ship" | "complete" | "cancel", revision: Number(v.expectedRevision) }; }
async function load(db: WorkerDatabaseClient, organization: string, id?: string, limit = 50) { const sql = id ? `SELECT t.*,COALESCE((SELECT json_agg(l ORDER BY l.created_at) FROM public.inventory_transfer_lines l WHERE l.transfer_id=t.id),'[]'::json) AS inventory_transfer_lines FROM public.inventory_transfers t WHERE t.organization_id=$1 AND t.id=$2 LIMIT 1` : `SELECT t.*,COALESCE((SELECT json_agg(l ORDER BY l.created_at) FROM public.inventory_transfer_lines l WHERE l.transfer_id=t.id),'[]'::json) AS inventory_transfer_lines FROM public.inventory_transfers t WHERE t.organization_id=$1 ORDER BY t.created_at DESC LIMIT $2`; const result = await db.query<Row>(sql, id ? [organization, id] : [organization, limit]); return result.rows.map((r) => ({ ...r, inventory_transfer_lines: Array.isArray(r.inventory_transfer_lines) ? r.inventory_transfer_lines : [] })); }
async function audit(db: WorkerDatabaseClient, action: string, id: string, organization: string, subject: string, details: Record<string, unknown>) { await db.query("INSERT INTO public.audit_logs (action,resource,details) VALUES ($1,$2,$3::jsonb)", [action, `inventory_transfer:${id}`, JSON.stringify({ organization_id: organization, actor_subject: subject, ...details })]); }

export async function handleInventoryTransferCollectionRequest(r: Request, app: WorkerDatabaseClient, commerce: WorkerDatabaseClient | undefined, env: Env): Promise<Response> {
  if (!["GET", "POST"].includes(r.method)) return json({ error: "method_not_allowed" }, 405); const c = await auth(r, env); if (c instanceof Response) return c; const organization = org(c); if (!organization) return json({ error: "organization_scope_required" }, 403);
  if (r.method === "GET") { if (!can(c, "read")) return json({ error: "forbidden" }, 403); const n = Number(new URL(r.url).searchParams.get("limit") ?? "50"); return json({ data: await load(app, organization, undefined, Number.isSafeInteger(n) && n > 0 ? Math.min(200, n) : 50), organizationId: organization }); }
  if (!can(c, "write")) return json({ error: "forbidden" }, 403); const idempotency = key(r); if (!idempotency) return json({ error: "idempotency_key_required" }, 400); const raw = await parse(r, 128 * 1024); if (raw instanceof Response) return raw; const input = create(raw); if (!input) return json({ error: "invalid_transfer_payload" }, 400); const scoped = await hash(`inventory-transfer:create:${organization}:${idempotency}`); const requestHash = await hash({ organization, ...input }); return (await executeIdempotently(new HyperdriveIdempotencyStore(app), scoped, requestHash, async () => { const made = await withWorkerTransaction(app, async (tx) => { const inserted = await tx.query<Row>(`INSERT INTO public.inventory_transfers (organization_id,source_location_id,destination_location_id,idempotency_key,created_by_email) VALUES ($1,$2,$3,$4,$5) RETURNING *`, [organization, input.source, input.destination, idempotency, typeof c.email === "string" ? c.email : c.sub]); const transfer = inserted.rows[0]; if (!transfer) throw new Error("transfer_create_failed"); for (const line of input.lines) await tx.query(`INSERT INTO public.inventory_transfer_lines (transfer_id,product_id,variant_id,quantity) VALUES ($1,$2,$3,$4)`, [transfer.id, line.product, line.variant, line.quantity]); await audit(tx, "inventory.transfer.create", transfer.id, organization, c.sub, { lines: input.lines.length }); return (await load(tx, organization, transfer.id))[0]; }); return json({ data: made }, 201); })).response;
}
export async function handleInventoryTransferDetailRequest(r: Request, app: WorkerDatabaseClient, env: Env, id: string): Promise<Response> { if (r.method !== "GET") return json({ error: "method_not_allowed" }, 405); if (!uuid(id)) return json({ error: "invalid_transfer_id" }, 400); const c = await auth(r, env); if (c instanceof Response) return c; const organization = org(c); if (!organization) return json({ error: "organization_scope_required" }, 403); if (!can(c, "read")) return json({ error: "forbidden" }, 403); const found = (await load(app, organization, id))[0]; return found ? json({ data: found }) : json({ error: "transfer_not_found" }, 404); }
export async function handleInventoryTransferMutationRequest(r: Request, app: WorkerDatabaseClient, commerce: WorkerDatabaseClient | undefined, env: Env, id: string): Promise<Response> {
  if (r.method !== "POST") return json({ error: "method_not_allowed" }, 405); if (!uuid(id)) return json({ error: "invalid_transfer_id" }, 400); const c = await auth(r, env); if (c instanceof Response) return c; const organization = org(c); if (!organization) return json({ error: "organization_scope_required" }, 403); if (!can(c, "write")) return json({ error: "forbidden" }, 403); const idempotency = key(r); if (!idempotency) return json({ error: "idempotency_key_required" }, 400); const raw = await parse(r, 16 * 1024); if (raw instanceof Response) return raw; const input = operation(raw); if (!input) return json({ error: "invalid_transfer_operation" }, 400); const scoped = await hash(`inventory-transfer:${organization}:${id}:${input.action}:${idempotency}`); const requestHash = await hash({ organization, id, ...input }); return (await executeIdempotently(new HyperdriveIdempotencyStore(app), scoped, requestHash, async () => { const transfer = (await load(app, organization, id))[0]; if (!transfer) return json({ error: "transfer_not_found" }, 404); if (transfer.revision !== input.revision) return json({ error: "transfer_conflict", code: "INVENTORY_TRANSFER_CONFLICT" }, 409); const allowed: Record<string, string[]> = { approve: ["draft"], ship: ["approved"], complete: ["in_transit"], cancel: ["draft", "approved", "in_transit"] }; if (!allowed[input.action].includes(transfer.status)) return json({ error: "transfer_invalid_state", code: "INVENTORY_TRANSFER_INVALID_STATE" }, 409);
    if (input.action !== "complete") { const next = input.action === "approve" ? "approved" : input.action === "ship" ? "in_transit" : "cancelled"; const updated = await withWorkerTransaction(app, async (tx) => { const result = await tx.query<Row>(`UPDATE public.inventory_transfers SET status=$1,revision=revision+1,updated_at=now() WHERE id=$2 AND organization_id=$3 AND revision=$4 RETURNING *`, [next, id, organization, input.revision]); if (!result.rows[0]) throw new Error("transfer_conflict"); await audit(tx, `inventory.transfer.${input.action}`, id, organization, c.sub, { status: next }); return (await load(tx, organization, id))[0]; }); return json({ data: updated }); }
    if (!commerce) return json({ error: "commerce_database_unavailable" }, 503); const lines = transfer.inventory_transfer_lines ?? []; await withWorkerTransaction(app, async (tx) => { const r = await tx.query(`UPDATE public.inventory_transfers SET status='processing',revision=revision+1,updated_at=now() WHERE id=$1 AND organization_id=$2 AND revision=$3`, [id, organization, input.revision]); if (!r.rowCount) throw new Error("transfer_conflict"); });
    try { await withWorkerTransaction(commerce, async (tx) => { for (const line of lines) { const source = await tx.query<{ inventory_item_id: string; stocked_quantity: number | string; reserved_quantity: number | string }>(`SELECT pvi.inventory_item_id,il.stocked_quantity,il.reserved_quantity FROM public.product_variant_inventory_item pvi JOIN public.product_variant v ON v.id=pvi.variant_id AND v.deleted_at IS NULL JOIN public.product p ON p.id=v.product_id AND p.deleted_at IS NULL JOIN public.inventory_level il ON il.inventory_item_id=pvi.inventory_item_id AND il.location_id=$2 AND il.deleted_at IS NULL WHERE v.id=$1 AND v.product_id=$3 AND p.metadata->>'organization_id'=$4 FOR UPDATE`, [line.variant_id, transfer.source_location_id, line.product_id, organization]); const destination = await tx.query<{ inventory_item_id: string; stocked_quantity: number | string; reserved_quantity: number | string }>(`SELECT pvi.inventory_item_id,il.stocked_quantity,il.reserved_quantity FROM public.product_variant_inventory_item pvi JOIN public.product_variant v ON v.id=pvi.variant_id AND v.deleted_at IS NULL JOIN public.product p ON p.id=v.product_id AND p.deleted_at IS NULL JOIN public.inventory_level il ON il.inventory_item_id=pvi.inventory_item_id AND il.location_id=$2 AND il.deleted_at IS NULL WHERE v.id=$1 AND v.product_id=$3 AND p.metadata->>'organization_id'=$4 FOR UPDATE`, [line.variant_id, transfer.destination_location_id, line.product_id, organization]); const s = source.rows[0], d = destination.rows[0]; if (!s || !d) throw new Error("inventory_unavailable"); const nextSource = Number(s.stocked_quantity) - line.quantity, nextDestination = Number(d.stocked_quantity) + line.quantity; if (nextSource < Number(s.reserved_quantity) || nextDestination > 1_000_000) throw new Error("insufficient_inventory"); await tx.query(`UPDATE public.inventory_level SET stocked_quantity=$1,updated_at=now() WHERE inventory_item_id=$2 AND location_id=$3`, [nextSource, s.inventory_item_id, transfer.source_location_id]); await tx.query(`UPDATE public.inventory_level SET stocked_quantity=$1,updated_at=now() WHERE inventory_item_id=$2 AND location_id=$3`, [nextDestination, d.inventory_item_id, transfer.destination_location_id]); } }); } catch (error) { const code = error instanceof Error && error.message === "insufficient_inventory" ? "INSUFFICIENT_INVENTORY" : "INVENTORY_TRANSFER_FAILED"; await app.query(`UPDATE public.inventory_transfers SET status='failed',failure_code=$1,failure_message='Unable to complete inventory transfer',revision=revision+1,updated_at=now() WHERE id=$2 AND organization_id=$3 AND status='processing'`, [code, id, organization]); return json({ error: "Unable to complete inventory transfer", code }, 409); }
    const completed = await withWorkerTransaction(app, async (tx) => { const result = await tx.query<Row>(`UPDATE public.inventory_transfers SET status='completed',revision=revision+1,completed_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2 AND status='processing' RETURNING *`, [id, organization]); if (!result.rows[0]) throw new Error("transfer_finalize_failed"); await audit(tx, "inventory.transfer.complete", id, organization, c.sub, { lines: lines.length }); return (await load(tx, organization, id))[0]; }); return json({ data: completed });
  })).response;
}
