import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";
import { withWorkerTransaction } from "./database.ts";

type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string };
type Row = Record<string, unknown>;
const accountProjection = "id,customer_email,medusa_customer_id,points_balance,lifetime_points,tier,birthday,phone,qr_token,created_at,updated_at";
const rewardProjection = "id,name,description,points_cost,reward_type,reward_value,is_active,created_at";
function json(body: Record<string, unknown>, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function can(c: WorkerAuthClaims, permission: string): boolean { const p = Array.isArray(c.permissions) ? c.permissions : []; return c.role === "owner" || c.role === "admin" || p.some((v) => v === "*" || v === permission); }
async function auth(r: Request, e: Env, permission: string): Promise<WorkerAuthClaims | Response> { const c = await verifyWorkerBearerToken(r.headers.get("Authorization"), { secret: e.CMS_ADMIN_JWT_SECRET, supabaseUrl: e.SUPABASE_URL }); if (!c) return json({ error: "unauthorized" }, 401); return can(c, permission) ? c : json({ error: "forbidden" }, 403); }
async function hash(v: unknown): Promise<string> { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(v))))].map((b) => b.toString(16).padStart(2, "0")).join(""); }
function account(row: Row): Row { return { id: String(row.id), customer_email: String(row.customer_email), medusa_customer_id: row.medusa_customer_id == null ? null : String(row.medusa_customer_id), points_balance: Number(row.points_balance) || 0, lifetime_points: Number(row.lifetime_points) || 0, tier: String(row.tier ?? "standard"), birthday: row.birthday == null ? null : String(row.birthday), phone: row.phone == null ? null : String(row.phone), qr_token: row.qr_token == null ? null : String(row.qr_token), created_at: String(row.created_at), updated_at: String(row.updated_at) }; }
function reward(row: Row): Row { return { id: String(row.id), name: String(row.name), description: row.description == null ? null : String(row.description), points_cost: Number(row.points_cost) || 0, reward_type: String(row.reward_type ?? "discount"), reward_value: row.reward_value && typeof row.reward_value === "object" ? row.reward_value : {}, is_active: Boolean(row.is_active), created_at: String(row.created_at) }; }
function text(v: unknown, max: number): string | null { return typeof v === "string" && v.trim() && v.length <= max ? v.trim() : null; }
async function parse(request: Request, max: number): Promise<Record<string, unknown> | Response> { try { const raw = await request.text(); if (raw.length > max) return json({ error: "payload_too_large" }, 413); const value = JSON.parse(raw); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : json({ error: "invalid_payload" }, 400); } catch { return json({ error: "invalid_json" }, 400); } }
function key(r: Request): string | Response { const value = r.headers.get("Idempotency-Key")?.trim(); return value || json({ error: "idempotency_key_required" }, 400); }
async function audit(db: WorkerDatabaseClient, action: string, resource: string, c: WorkerAuthClaims, details: Record<string, unknown> = {}): Promise<void> { await db.query("INSERT INTO public.audit_logs (action,resource,details) VALUES ($1,$2,$3::jsonb)", [action, resource, JSON.stringify({ actor_subject: c.sub, ...details })]); }

export async function handleAdminLoyaltyRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  if (request.method !== "GET" && request.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  const c = await auth(request, env, request.method === "GET" ? "loyalty:read" : "loyalty:write"); if (c instanceof Response) return c;
  if (request.method === "GET") { const tier = new URL(request.url).searchParams.get("tier"); if (tier && !["standard", "silver", "gold", "platinum"].includes(tier)) return json({ error: "invalid_tier" }, 400); const result = await database.query<Row>(`SELECT ${accountProjection} FROM public.loyalty_accounts ${tier ? "WHERE tier=$1" : ""} ORDER BY lifetime_points DESC LIMIT 500`, tier ? [tier] : []); return json({ data: result.rows.map(account) }); }
  const idempotency = key(request); if (idempotency instanceof Response) return idempotency; const input = await parse(request, 32 * 1024); if (input instanceof Response) return input; const email = text(input.email, 320)?.toLowerCase(); if (!email || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) return json({ error: "invalid_email" }, 400); const customerId = text(input.medusa_customer_id, 200); const hashValue = await hash({ email, customerId });
  return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `loyalty-account:${email}:${idempotency}`, hashValue, async () => { const existing = await database.query<Row>(`SELECT ${accountProjection} FROM public.loyalty_accounts WHERE customer_email=$1 LIMIT 1`, [email]); if (existing.rows[0]) return json({ data: account(existing.rows[0]) }); const inserted = await database.query<Row>(`INSERT INTO public.loyalty_accounts (customer_email,medusa_customer_id) VALUES ($1,$2) RETURNING ${accountProjection}`, [email, customerId]); const row = inserted.rows[0]; if (!row) return json({ error: "loyalty_account_unavailable" }, 503); await audit(database, "loyalty.account.create", `loyalty-account:${row.id}`, c); return json({ data: account(row) }, 201); })).response;
}

export async function handleAdminLoyaltyPointsRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  if (request.method !== "POST") return json({ error: "method_not_allowed" }, 405); const c = await auth(request, env, "loyalty:write"); if (c instanceof Response) return c; const idempotency = key(request); if (idempotency instanceof Response) return idempotency; const input = await parse(request, 32 * 1024); if (input instanceof Response) return input;
  const accountId = text(input.account_id, 200); const points = input.points; const reason = text(input.reason, 500); const action = input.action === "redeem" ? "redeem" : input.action === "add" || input.action === undefined ? "add" : null; if (!accountId || !Number.isInteger(points) || (points as number) <= 0 || (points as number) > 1_000_000 || !reason || !action) return json({ error: "invalid_points_payload" }, 400); const delta = action === "redeem" ? -(points as number) : points as number; const hashValue = await hash({ accountId, points, reason, action, orderId: input.order_id });
  return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `loyalty-points:${accountId}:${idempotency}`, hashValue, async () => { const result = await withWorkerTransaction(database, async (tx) => { const current = await tx.query<Row>(`SELECT points_balance,lifetime_points FROM public.loyalty_accounts WHERE id=$1 FOR UPDATE`, [accountId]); const row = current.rows[0]; if (!row) return null; const balance = Number(row.points_balance); if (action === "redeem" && balance < (points as number)) return { __error: "insufficient_points" }; const lifetime = Number(row.lifetime_points) + (delta > 0 ? delta : 0); const tier = lifetime >= 10000 ? "platinum" : lifetime >= 5000 ? "gold" : lifetime >= 1000 ? "silver" : "standard"; await tx.query("INSERT INTO public.loyalty_transactions (loyalty_account_id,points_delta,reason,order_id,medusa_order_id) VALUES ($1,$2,$3,$4,$4)", [accountId, delta, reason, text(input.order_id, 200)]); const updated = await tx.query<Row>(`UPDATE public.loyalty_accounts SET points_balance=$2,lifetime_points=$3,tier=$4,updated_at=now() WHERE id=$1 RETURNING ${accountProjection}`, [accountId, balance + delta, lifetime, tier]); return updated.rows[0] ?? null; }); if (result && result.__error === "insufficient_points") return json({ error: "insufficient_points" }, 409); if (!result) return json({ error: "loyalty_account_not_found" }, 404); await audit(database, `loyalty.points.${action}`, `loyalty-account:${accountId}`, c, { points: delta }); return json({ data: account(result) }); })).response;
}

export async function handleAdminLoyaltyRewardsRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  if (request.method !== "GET" && request.method !== "POST") return json({ error: "method_not_allowed" }, 405); const c = await auth(request, env, request.method === "GET" ? "loyalty:read" : "loyalty:write"); if (c instanceof Response) return c;
  if (request.method === "GET") { const result = await database.query<Row>(`SELECT ${rewardProjection} FROM public.loyalty_rewards WHERE is_active=true ORDER BY points_cost LIMIT 500`); return json({ data: result.rows.map(reward) }); }
  const idempotency = key(request); if (idempotency instanceof Response) return idempotency; const input = await parse(request, 64 * 1024); if (input instanceof Response) return input; const name = text(input.name, 200); const description = text(input.description, 2000); const pointsCost = input.points_cost; const type = text(input.reward_type, 32) ?? "discount"; if (!name || !Number.isInteger(pointsCost) || (pointsCost as number) <= 0 || (pointsCost as number) > 1_000_000 || !["discount", "free_item", "free_shipping", "custom"].includes(type)) return json({ error: "invalid_reward_payload" }, 400); const value = input.reward_value && typeof input.reward_value === "object" && !Array.isArray(input.reward_value) ? input.reward_value : {}; const hashValue = await hash({ name, description, pointsCost, type, value });
  return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `loyalty-reward:${idempotency}`, hashValue, async () => { const result = await database.query<Row>(`INSERT INTO public.loyalty_rewards (name,description,points_cost,reward_type,reward_value) VALUES ($1,$2,$3,$4,$5::jsonb) RETURNING ${rewardProjection}`, [name, description, pointsCost, type, JSON.stringify(value)]); const row = result.rows[0]; if (!row) return json({ error: "loyalty_reward_unavailable" }, 503); await audit(database, "loyalty.reward.create", `loyalty-reward:${row.id}`, c); return json({ data: reward(row) }, 201); })).response;
}

export async function handleAdminLoyaltyLookupRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  if (request.method !== "GET") return json({ error: "method_not_allowed" }, 405); const c = await auth(request, env, "loyalty:read"); if (c instanceof Response) return c; const params = new URL(request.url).searchParams; const qr = params.get("qr")?.trim() ?? ""; const phone = params.get("phone")?.trim() ?? ""; if ((qr && phone) || (!qr && !phone)) return json({ error: "qr_or_phone_required" }, 400); const value = qr || phone; if (value.length > 200) return json({ error: "lookup_value_too_long" }, 400); const column = qr ? "qr_token" : "phone"; const result = await database.query<Row>(`SELECT ${accountProjection} FROM public.loyalty_accounts WHERE ${column}=$1 LIMIT 1`, [value]); return result.rows[0] ? json({ data: account(result.rows[0]) }) : json({ error: "not_found" }, 404);
}
