import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";

type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string };
type QueueRow = { id: string; device_name: string; employee_id: string | null; payload: Record<string, unknown>; status: "pending" | "synced" | "failed"; error_message: string | null; created_at: string; synced_at: string | null };
function json(body: Record<string, unknown>, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function org(claims: WorkerAuthClaims): string | null { const value = claims.organization_id ?? claims.org_id; return typeof value === "string" && value.trim() ? value.trim() : null; }
function allowed(claims: WorkerAuthClaims): boolean { const permissions = Array.isArray(claims.permissions) ? claims.permissions : []; return claims.role === "owner" || claims.role === "admin" || permissions.some((value) => value === "*" || value === "pos:use"); }
function row(value: QueueRow): Record<string, unknown> { return { id: String(value.id), device_name: String(value.device_name), employee_id: value.employee_id == null ? null : String(value.employee_id), payload: value.payload && typeof value.payload === "object" && !Array.isArray(value.payload) ? value.payload : {}, status: value.status, error_message: value.error_message == null ? null : String(value.error_message).slice(0, 2000), created_at: String(value.created_at), synced_at: value.synced_at == null ? null : String(value.synced_at) }; }
async function hash(value: unknown): Promise<string> { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))))].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function readBody(request: Request): Promise<unknown> { const length = Number(request.headers.get("content-length") ?? 0); if (length > 256 * 1024) throw new Error("payload_too_large"); const text = await request.text(); if (text.length > 256 * 1024) throw new Error("payload_too_large"); return JSON.parse(text); }

export async function handleAdminOfflineQueueRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  if (!["GET", "POST", "PATCH"].includes(request.method)) return json({ error: "method_not_allowed" }, 405);
  const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL });
  if (!claims) return json({ error: "unauthorized" }, 401);
  if (!allowed(claims)) return json({ error: "forbidden" }, 403);
  const organizationId = org(claims); if (!organizationId) return json({ error: "organization_claim_required" }, 403);
  if (request.method === "GET") {
    const url = new URL(request.url); const device = url.searchParams.get("device")?.trim(); if (device && device.length > 200) return json({ error: "invalid_device" }, 400); const rawLimit = Number(url.searchParams.get("limit") ?? 100); const limit = Number.isInteger(rawLimit) ? Math.min(Math.max(rawLimit, 1), 100) : 100;
    const clauses = ["organization_id=$1", "status='pending'"]; const values: unknown[] = [organizationId]; if (device) { clauses.push(`device_name=$${values.length + 1}`); values.push(device); } values.push(limit); const result = await database.query<QueueRow>(`SELECT id,device_name,employee_id,payload,status,error_message,created_at,synced_at FROM public.offline_pos_queue WHERE ${clauses.join(" AND ")} ORDER BY created_at ASC LIMIT $${values.length}`, values); return json({ data: result.rows.map(row) });
  }
  const key = request.headers.get("Idempotency-Key")?.trim(); if (!key) return json({ error: "idempotency_key_required" }, 400);
  let body: Record<string, unknown>; try { const parsed = await readBody(request); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return json({ error: "invalid_payload" }, 400); body = parsed as Record<string, unknown>; } catch (error) { return json({ error: error instanceof Error && error.message === "payload_too_large" ? "payload_too_large" : "invalid_json" }, error instanceof Error && error.message === "payload_too_large" ? 413 : 400); }
  if (request.method === "POST") {
    const device = typeof body.device_name === "string" ? body.device_name.trim() : ""; const employeeId = typeof body.employee_id === "string" ? body.employee_id.trim() : null; const payload = body.payload; if (!device || device.length > 200 || (employeeId !== null && employeeId.length > 200) || !payload || typeof payload !== "object" || Array.isArray(payload) || Object.keys(payload).length > 100) return json({ error: "invalid_payload" }, 400);
    const result = await executeIdempotently(new HyperdriveIdempotencyStore(database), `offline-queue:${organizationId}:${key}`, await hash({ organizationId, device, employeeId, payload }), async () => { const inserted = await database.query<QueueRow>("INSERT INTO public.offline_pos_queue (organization_id,device_name,employee_id,payload,status) VALUES ($1,$2,$3,$4::jsonb,'pending') RETURNING id,device_name,employee_id,payload,status,error_message,created_at,synced_at", [organizationId, device, employeeId, JSON.stringify(payload)]); const item = inserted.rows[0]; return item ? json({ data: row(item) }, 201) : json({ error: "queue_unavailable" }, 503); }); return result.response;
  }
  const id = typeof body.id === "string" ? body.id.trim() : ""; const action = body.action; const errorMessage = typeof body.error_message === "string" ? body.error_message.trim().slice(0, 2000) : "Unknown error"; if (!id || id.length > 200 || (action !== "synced" && action !== "failed")) return json({ error: "invalid_payload" }, 400);
  const result = await executeIdempotently(new HyperdriveIdempotencyStore(database), `offline-queue:${organizationId}:${key}`, await hash({ organizationId, id, action, errorMessage }), async () => { const updated = action === "synced" ? await database.query("UPDATE public.offline_pos_queue SET status='synced',synced_at=now() WHERE id=$1 AND organization_id=$2 AND status='pending' RETURNING id", [id, organizationId]) : await database.query("UPDATE public.offline_pos_queue SET status='failed',error_message=$1 WHERE id=$2 AND organization_id=$3 AND status='pending' RETURNING id", [errorMessage, id, organizationId]); return updated.rowCount ? json({ success: true }) : json({ error: "queue_item_not_found" }, 404); }); return result.response;
}
