import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";

type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string };
const json = (body: Record<string, unknown>, status = 200) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } });
const tenant = (claims: WorkerAuthClaims) => { const value = claims.organization_id ?? claims.org_id; return typeof value === "string" && value.trim() ? value.trim() : null; };
const allowed = (claims: WorkerAuthClaims) => claims.role === "owner" || claims.role === "admin" || (Array.isArray(claims.permissions) && claims.permissions.some((value) => value === "*" || value === "orders:write"));
export async function handleAdminPaymentMarkReviewRequest(request: Request, database: WorkerDatabaseClient, env: Env, correlationId: string): Promise<Response> {
  const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL }); if (!claims) return json({ error: "unauthorized", requestId: correlationId }, 401); if (!allowed(claims)) return json({ error: "forbidden", requestId: correlationId }, 403); const organizationId = tenant(claims); if (!organizationId) return json({ error: "organization_claim_required", requestId: correlationId }, 403); if (request.method !== "POST") return json({ error: "method_not_allowed", requestId: correlationId }, 405); const match = new URL(request.url).pathname.match(/^\/(?:api\/)?admin\/payments\/([^/]+)\/mark-review$/); const id = match ? decodeURIComponent(match[1]) : null; if (!id || id.length > 200) return json({ error: "invalid_payment_id", requestId: correlationId }, 400); const key = request.headers.get("Idempotency-Key")?.trim(); if (!key || key.length > 255) return json({ error: "idempotency_key_required", requestId: correlationId }, 400); const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify({ organizationId, id }))).then((bytes) => Array.from(new Uint8Array(bytes), (value) => value.toString(16).padStart(2, "0")).join("")); const actor = typeof claims.email === "string" ? claims.email : claims.sub; return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `payment-mark-review:${organizationId}:${id}:${key}`, hash, async () => { const row = await database.query("SELECT id, last_error FROM public.payment_attempts WHERE organization_id=$1 AND correlation_id=$2 LIMIT 1", [organizationId, id]); if (!row.rows[0]) return json({ error: "not_found", requestId: correlationId }, 404); const prior = String(row.rows[0].last_error ?? "").replace(/[\r\n\t]+/g, " ").slice(0, 450); const lastError = `${prior}${prior ? "; " : ""}escalated_by_operator`; await database.query("UPDATE public.payment_attempts SET status='needs_review', checkout_state='needs_review', last_error=$1, updated_at=now() WHERE organization_id=$2 AND correlation_id=$3", [lastError, organizationId, id]); await database.query("INSERT INTO public.audit_logs (action,resource,details) VALUES ($1,$2,$3::jsonb)", ["payment.mark_review", `payment_attempt:${id}`, JSON.stringify({ organization_id: organizationId, actor_subject: actor })]); return json({ ok: true }); })).response;
}
