import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";

type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string };
const json = (body: Record<string, unknown>, status = 200) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } });
const tenant = (c: WorkerAuthClaims) => { const value = c.organization_id ?? c.org_id; return typeof value === "string" && value.trim() ? value.trim() : null; };
const canRead = (c: WorkerAuthClaims) => c.role === "owner" || c.role === "admin" || (Array.isArray(c.permissions) && c.permissions.some((p) => p === "*" || p === "dashboard:read"));
const providers = ["stripe", "paypal", "xendit", "cod"] as const;
const confirmed = new Set(["paid", "authorized", "completed", "pending_capture", "paid_awaiting_order", "finalizing_order"]);
const open = new Set(["initiated", "pending_provider_redirect", "awaiting_completion", "paid_awaiting_order", "finalizing_order"]);
const problem = new Set(["expired", "needs_review", "failed"]);
const safe = (v: unknown, max = 500) => v == null ? null : String(v).replace(/[\r\n\t]+/g, " ").slice(0, max);
type ReconciliationRow = { date: string; provider: string; medusaOrderCount: number; medusaTotalMinor: number; providerConfirmedCount: number; providerConfirmedMinor: number; openAttemptCount: number; problemAttemptCount: number; discrepancyMinor: number; status: "matched" | "discrepancy" | "pending" };

export async function handleAdminReconciliationRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  if (request.method !== "GET") return json({ error: "method_not_allowed" }, 405);
  const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL });
  if (!claims) return json({ error: "unauthorized" }, 401); if (!canRead(claims)) return json({ error: "forbidden" }, 403);
  const organizationId = tenant(claims); if (!organizationId) return json({ error: "organization_claim_required" }, 403);
  const params = new URL(request.url).searchParams; const days = params.get("days") == null ? 14 : Number(params.get("days")); const provider = params.get("provider") ?? "all";
  if (!Number.isInteger(days) || days < 1 || days > 90 || (provider !== "all" && !providers.includes(provider as typeof providers[number]))) return json({ error: "invalid_query" }, 400);
  const now = new Date(); const floor = new Date(now); floor.setUTCDate(floor.getUTCDate() - (days - 1)); floor.setUTCHours(0, 0, 0, 0); const visibleProviders = provider === "all" ? [...providers] : [provider];
  const rows: ReconciliationRow[] = visibleProviders.flatMap((p) => Array.from({ length: days }, (_, i) => { const date = new Date(now); date.setUTCDate(date.getUTCDate() - i); return { date: date.toISOString().slice(0, 10), provider: p, medusaOrderCount: 0, medusaTotalMinor: 0, providerConfirmedCount: 0, providerConfirmedMinor: 0, openAttemptCount: 0, problemAttemptCount: 0, discrepancyMinor: 0, status: "pending" }; }));
  const attemptResult = await database.query("SELECT correlation_id, provider, status, checkout_state, amount_minor, provider_payment_id, webhook_last_status, medusa_order_id, stale_reason, last_error, updated_at, finalized_at, created_at FROM public.payment_attempts WHERE organization_id=$1 AND updated_at >= $2::timestamptz ORDER BY updated_at DESC LIMIT 500", [organizationId, floor.toISOString()]);
  const settlementValues: unknown[] = [organizationId, floor.toISOString()]; let settlementSql = "SELECT provider, external_id, status, amount_minor, currency, medusa_order_id, mismatch_reason, provider_occurred_at, updated_at FROM public.payment_settlement_records WHERE organization_id=$1 AND updated_at >= $2::timestamptz"; if (provider !== "all" && provider !== "cod") { settlementValues.push(provider); settlementSql += ` AND provider=$${settlementValues.length}`; } settlementSql += " ORDER BY updated_at DESC LIMIT 500";
  const artifactValues: unknown[] = [organizationId]; let artifactSql = "SELECT provider, status, external_id, metadata, idempotency_key, updated_at FROM public.payment_provider_artifacts WHERE organization_id=$1 AND artifact_type='reconciliation'"; if (provider !== "all" && provider !== "cod") { artifactValues.push(provider); artifactSql += ` AND provider=$${artifactValues.length}`; } artifactSql += " ORDER BY updated_at DESC LIMIT 25";
  const [settlements, artifacts, stale, needsReview] = await Promise.all([
    database.query(settlementSql, settlementValues), database.query(artifactSql, artifactValues),
    database.query("SELECT COUNT(*)::int AS count FROM public.payment_attempts WHERE organization_id=$1 AND status IN ('paid_awaiting_order','finalizing_order','paid') AND medusa_order_id IS NULL", [organizationId]),
    database.query("SELECT COUNT(*)::int AS count FROM public.payment_attempts WHERE organization_id=$1 AND status='needs_review'", [organizationId]),
  ]);
  const map = new Map(rows.map((row) => [`${row.date}:${row.provider}`, row])); const hasSettlements = settlements.rows.length > 0;
  for (const attempt of attemptResult.rows) { const date = String(attempt.finalized_at ?? attempt.updated_at ?? attempt.created_at).slice(0, 10); const row = map.get(`${date}:${attempt.provider}`); if (!row) continue; const amount = Number(attempt.amount_minor) || 0; if (attempt.medusa_order_id) { row.medusaOrderCount++; row.medusaTotalMinor += amount; } if (!hasSettlements && (attempt.provider_payment_id || attempt.webhook_last_status || confirmed.has(String(attempt.status)))) { row.providerConfirmedCount++; row.providerConfirmedMinor += amount; } if (open.has(String(attempt.status))) row.openAttemptCount++; if (problem.has(String(attempt.status))) row.problemAttemptCount++; }
  for (const settlement of settlements.rows) { const row = map.get(`${String(settlement.provider_occurred_at ?? settlement.updated_at).slice(0, 10)}:${settlement.provider}`); if (!row) continue; const amount = settlement.amount_minor == null ? 0 : Number(settlement.amount_minor); if (settlement.status === "matched" || settlement.status === "resolved") { row.providerConfirmedCount++; row.providerConfirmedMinor += Number.isFinite(amount) ? amount : 0; } else row.problemAttemptCount++; }
  for (const row of rows) { row.discrepancyMinor = row.medusaTotalMinor - row.providerConfirmedMinor; row.status = row.problemAttemptCount || row.openAttemptCount ? "pending" : row.discrepancyMinor !== 0 || row.medusaOrderCount !== row.providerConfirmedCount ? "discrepancy" : row.medusaOrderCount || row.providerConfirmedCount ? "matched" : "pending"; }
  const recentProblemAttempts = attemptResult.rows.filter((r) => ["expired", "needs_review", "paid_awaiting_order", "finalizing_order"].includes(String(r.status))).slice(0, 8).map((r) => ({ correlationId: String(r.correlation_id), provider: String(r.provider), status: String(r.status), checkoutState: String(r.checkout_state), staleReason: safe(r.stale_reason ?? r.last_error), updatedAt: String(r.updated_at) }));
  return json({ period: `Last ${days} days`, rows, totalMedusaMinor: rows.reduce((s, r) => s + r.medusaTotalMinor, 0), totalProviderConfirmedMinor: rows.reduce((s, r) => s + r.providerConfirmedMinor, 0), totalDiscrepancyMinor: rows.reduce((s, r) => s + r.discrepancyMinor, 0), paymentAttemptsStaleFinalize: Number(stale.rows[0]?.count) || 0, paymentAttemptsNeedsReview: Number(needsReview.rows[0]?.count) || 0, recentProblemAttempts, providerReconciliationArtifacts: artifacts.rows.map((r) => ({ provider: String(r.provider), status: String(r.status), externalId: String(r.external_id), jobId: r.metadata && typeof r.metadata === "object" && typeof (r.metadata as Record<string, unknown>).job_id === "string" ? (r.metadata as Record<string, unknown>).job_id : null, periodStart: r.metadata && typeof r.metadata === "object" && typeof (r.metadata as Record<string, unknown>).period_start === "string" ? (r.metadata as Record<string, unknown>).period_start : null, periodEnd: r.metadata && typeof r.metadata === "object" && typeof (r.metadata as Record<string, unknown>).period_end === "string" ? (r.metadata as Record<string, unknown>).period_end : null, idempotencyKey: r.idempotency_key == null ? null : String(r.idempotency_key), updatedAt: String(r.updated_at) })), providerSettlementRecords: settlements.rows.map((r) => ({ provider: String(r.provider), externalId: String(r.external_id), status: String(r.status), amountMinor: r.amount_minor == null ? null : Number(r.amount_minor), currency: r.currency == null ? null : String(r.currency), orderId: r.medusa_order_id == null ? null : String(r.medusa_order_id), mismatchReason: r.mismatch_reason == null ? null : safe(r.mismatch_reason) })) });
}
