import assert from "node:assert/strict";
import test from "node:test";
import { createHmac } from "node:crypto";
import { handleAdminSegmentMembersRequest, handleAdminSegmentsRequest } from "./segments-admin.ts";

function token(): string { const enc = (v: unknown) => Buffer.from(JSON.stringify(v)).toString("base64url"); const h = enc({ alg: "HS256", typ: "JWT" }); const p = enc({ sub: "staff_1", role: "admin", organization_id: "org_1", exp: Math.floor(Date.now() / 1000) + 300 }); return `${h}.${p}.${createHmac("sha256", "secret").update(`${h}.${p}`).digest("base64url")}`; }
test("segments are tenant-scoped, bounded, and mutations are durably idempotent", async () => {
  const statements: string[] = [];
  const database = { query: async <T extends Record<string, unknown>>(text: string, values: readonly unknown[] = []) => { statements.push(text); if (text.includes("INSERT INTO public.worker_idempotency_records")) return { rows: [{ state: "pending", request_hash: values[1] }], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("UPDATE public.worker_idempotency_records") || text.startsWith("DELETE FROM public.worker_idempotency_records")) return { rows: [], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("INSERT INTO public.customer_segments")) return { rows: [{ id: "s1", name: "VIP", description: null, rule_type: "manual", rule_config: {}, auto_refresh: true, member_count: 0, last_refreshed_at: null, created_at: "2026-09-21T00:00:00.000Z", organization_id: "org_1" }], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("SELECT id FROM public.customer_segments")) return { rows: [{ id: "s1" }], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("SELECT customer_email")) return { rows: [{ customer_email: "a@example.com", medusa_customer_id: null }], rowCount: 1 } as { rows: T[]; rowCount: number }; if (text.startsWith("SELECT COUNT")) return { rows: [{ count: 1 }], rowCount: 1 } as { rows: T[]; rowCount: number }; return { rows: [], rowCount: 0 } as { rows: T[]; rowCount: number }; }, end: async () => {} };
  const auth = { Authorization: `Bearer ${token()}`, "Content-Type": "application/json" };
  const list = await handleAdminSegmentsRequest(new Request("https://api.test/api/admin/segments", { headers: auth }), database, { CMS_ADMIN_JWT_SECRET: "secret" }); assert.equal(list.status, 200);
  const created = await handleAdminSegmentsRequest(new Request("https://api.test/api/admin/segments", { method: "POST", headers: { ...auth, "Idempotency-Key": "segment-1" }, body: JSON.stringify({ name: "VIP", rule_type: "manual" }) }), database, { CMS_ADMIN_JWT_SECRET: "secret" }); assert.equal(created.status, 201);
  const members = await handleAdminSegmentMembersRequest(new Request("https://api.test/api/admin/segments/s1/members", { method: "POST", headers: { ...auth, "Idempotency-Key": "members-1" }, body: JSON.stringify({ members: [{ customer_email: "A@example.com" }] }) }), database, { CMS_ADMIN_JWT_SECRET: "secret" }, "s1"); assert.equal(members.status, 200);
  assert.ok(statements.some((statement) => statement.includes("organization_id=$1") && statement.includes("LIMIT 500")));
});
