import type { WorkerDatabaseClient } from "./database.ts";
import { verifyWorkerBearerToken, type WorkerAuthClaims } from "./auth.ts";
import { executeIdempotently, HyperdriveIdempotencyStore } from "./idempotency.ts";

type Env = { CMS_ADMIN_JWT_SECRET?: string; SUPABASE_URL?: string; ADMIN_STEP_UP_REQUIRED?: string; ADMIN_STEP_UP_SECRET?: string; TERMINAL_DEVICE_BINDING_REQUIRED?: string; TERMINAL_AGENT_URL?: string; TERMINAL_AGENT_SECRET?: string };
const json = (body: Record<string, unknown>, status = 200) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } });
const can = (c: WorkerAuthClaims) => c.role === "owner" || c.role === "admin" || (Array.isArray(c.permissions) && c.permissions.some((p) => p === "*" || p === "pos:use"));
const equal = (a: string, b: string) => a.length === b.length && [...a].reduce((n, _, i) => n | (a.charCodeAt(i) ^ b.charCodeAt(i)), 0) === 0;
async function stepUpValid(request: Request, env: Env): Promise<boolean> { if (env.ADMIN_STEP_UP_REQUIRED !== "true") return true; const value = request.headers.get("x-admin-step-up")?.trim() ?? ""; const match = value.match(/^terminal\.open_drawer\.(\d+)\.([0-9a-f]+)$/); if (!match || !env.ADMIN_STEP_UP_SECRET) return false; const expires = Number(match[1]); if (!Number.isSafeInteger(expires) || expires < Math.floor(Date.now() / 1000)) return false; const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(env.ADMIN_STEP_UP_SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const expected = [...new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(`terminal.open_drawer.${expires}`)))].map((v) => v.toString(16).padStart(2, "0")).join(""); return equal(expected, match[2]); }

export async function handleAdminTerminalOpenDrawerRequest(request: Request, database: WorkerDatabaseClient, env: Env): Promise<Response> {
  if (request.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  const claims = await verifyWorkerBearerToken(request.headers.get("Authorization"), { secret: env.CMS_ADMIN_JWT_SECRET, supabaseUrl: env.SUPABASE_URL }); if (!claims) return json({ error: "unauthorized" }, 401); if (!can(claims)) return json({ error: "forbidden" }, 403); if (!(await stepUpValid(request, env))) return json({ error: "step_up_required" }, 403);
  const key = request.headers.get("Idempotency-Key")?.trim(); if (!key || key.length > 255) return json({ error: "idempotency_key_required" }, 400);
  let input: Record<string, unknown>; try { const raw = await request.arrayBuffer(); if (raw.byteLength > 16 * 1024) return json({ error: "payload_too_large" }, 413); const value = JSON.parse(new TextDecoder().decode(raw)) as unknown; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(); input = value as Record<string, unknown>; } catch { return json({ error: "invalid_payload" }, 400); }
  const deviceId = request.headers.get("x-device-id")?.trim() || (typeof input.device_id === "string" ? input.device_id.trim() : ""); const reason = typeof input.reason === "string" ? input.reason.trim().slice(0, 200) : "";
  if (deviceId.length > 128 || !reason) return json({ error: "invalid_payload" }, 400);
  if (env.TERMINAL_DEVICE_BINDING_REQUIRED === "true") { const token = request.headers.get("x-device-token")?.trim(); if (!deviceId || !token) return json({ error: "device_authentication_required" }, 403); const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(token)); const hash = Array.from(new Uint8Array(digest), (v) => v.toString(16).padStart(2, "0")).join(""); const ip = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || null; const binding = await database.query<{ bound_ip: string | null }>("SELECT bound_ip FROM public.pos_device_bindings WHERE device_id=$1 AND token_hash=$2 AND is_active=true AND revoked_at IS NULL LIMIT 1", [deviceId, hash]); if (!binding.rows[0] || binding.rows[0].bound_ip && binding.rows[0].bound_ip !== ip) return json({ error: "device_authentication_failed" }, 403); }
  const base = env.TERMINAL_AGENT_URL?.trim(); if (!base) return json({ error: "terminal_agent_unavailable" }, 503); let target: URL; try { target = new URL(`${base.replace(/\/$/, "")}/open-drawer`); if (target.protocol !== "https:" && !(target.protocol === "http:" && ["localhost", "127.0.0.1"].includes(target.hostname))) throw new Error(); } catch { return json({ error: "terminal_agent_unavailable" }, 503); }
  const requestHashBytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify({ deviceId, reason }))); const requestHash = Array.from(new Uint8Array(requestHashBytes), (v) => v.toString(16).padStart(2, "0")).join("");
  return (await executeIdempotently(new HyperdriveIdempotencyStore(database), `terminal-drawer:${claims.sub}:${key}`, requestHash, async () => { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 5000); try { const response = await fetch(target, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json", ...(env.TERMINAL_AGENT_SECRET ? { "X-Terminal-Agent-Secret": env.TERMINAL_AGENT_SECRET } : {}) }, body: JSON.stringify({ device_id: deviceId || undefined, reason }), signal: controller.signal }); const declared = Number(response.headers.get("content-length") ?? 0); if (declared > 1024 * 1024) return json({ error: "terminal_agent_invalid_response" }, 502); const text = await response.text(); if (new TextEncoder().encode(text).byteLength > 1024 * 1024) return json({ error: "terminal_agent_invalid_response" }, 502); let payload: unknown; try { payload = text ? JSON.parse(text) : {}; } catch { return json({ error: "terminal_agent_invalid_response" }, 502); } if (!response.ok || !payload || typeof payload !== "object") return json({ error: "terminal_agent_failed" }, response.status >= 500 ? 503 : response.status); return json(payload as Record<string, unknown>, response.status); } catch { return json({ error: "terminal_agent_unavailable" }, 503); } finally { clearTimeout(timer); } })).response;
}
