/** Stable codes returned by `/api/checkout/available-payment-methods` (client-safe). */

export const CHECKOUT_AVAILABILITY = {
  OK: "OK",
  WORKER_API_URL_MISSING: "WORKER_API_URL_MISSING",
  WORKER_PAYMENT_METHODS_UNAVAILABLE: "WORKER_PAYMENT_METHODS_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PAYMENT_METHODS_LOAD_FAILED: "PAYMENT_METHODS_LOAD_FAILED",
} as const;

const CHECKOUT_HARD_UNAVAILABLE_CODES: ReadonlySet<string> = new Set([
  CHECKOUT_AVAILABILITY.WORKER_API_URL_MISSING,
  CHECKOUT_AVAILABILITY.WORKER_PAYMENT_METHODS_UNAVAILABLE,
  CHECKOUT_AVAILABILITY.INTERNAL_ERROR,
  CHECKOUT_AVAILABILITY.PAYMENT_METHODS_LOAD_FAILED,
]);

export function isCheckoutHardUnavailableCode(
  code: string | undefined,
): boolean {
  return Boolean(code && CHECKOUT_HARD_UNAVAILABLE_CODES.has(code));
}
